### ISSUE TITLE
VB -> C#: With and NameOf not working together (causes MemberAccessExpressionSyntax error)

### ISSUE THREAD

**Issue by jrmoreno1** [icsharpcode/CodeConverter#1002]
### VB.Net input code
```vbnet
Public Class VisualBasicClass

Sub Main
Dim t as DataTable = nothing 

Dim businessGroups = t.AsEnumerable().
                                 Select(Function(rw)  New MyDto() With {
                                                       .Id = rw.GetValueOrDefault(Of Integer)(NameOf(.Id)),
                                                       .Bg = rw.GetValueOrDefault(Of String)(NameOf(.Bg)),
                                                       .Description = Markdig.Markdown.
                                                       Parse(rw.GetValueOrDefault(Of String)(NameOf(.Description)).ToSafeString()).ToHtml()
                                                       })
End Sub
```

### Erroneous output
```C#
using System.Linq;

public partial class VisualBasicClass
{

    public void Main()
    {
        DataTable t = default;

        var businessGroups = t.AsEnumerable().Select(rw => new MyDto()
        {
            Id = rw.GetValueOrDefault<int>(nameof(default
#error Cannot convert MemberAccessExpressionSyntax - see comment for details
/* Cannot convert MemberAccessExpressionSyntax, System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 461
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 38

Input:
.Id
 */
)),
            Bg = rw.GetValueOrDefault<string>(nameof(default
#error Cannot convert MemberAccessExpressionSyntax - see comment for details
/* Cannot convert MemberAccessExpressionSyntax, System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 461
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 38

Input:
.Bg
 */
)),
            Description = Markdig.Markdown.Parse(rw.GetValueOrDefault<string>(nameof(default
#error Cannot convert MemberAccessExpressionSyntax - see comment for details
/* Cannot convert MemberAccessExpressionSyntax, System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 461
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 38

Input:
.Description
 */
)).ToSafeString()).ToHtml()
        });
    }

}
```

### Expected output
```C#
using System.Linq;

public partial class VisualBasicClass
{

    public void Main()
    {
        DataTable t = default;

        var businessGroups = t.AsEnumerable().Select(rw => new MyDto()
        {
            Id = rw.GetValueOrDefault<int>(nameof(MyDto.Id)),
            Bg = rw.GetValueOrDefault<string>(nameof(MyDto.Bg)),
            Description = Markdig.Markdown.Parse(rw.GetValueOrDefault<string>(nameof(MyDto.Description)).ToSafeString()).ToHtml()
        });
    }

}
```

### Details
* Product in use: both
* Version in use: 9.2.1.0
* Did you see it working in a previous version: No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the report and repro! The problem is that when I wrote the code for those object initializer blocks, I obviously never conceived of someone reading from an existing property of the created object within it. So anything at all that does that will blow up I think. e.g. Even without the nameof, this would blow up

```vbnet
Public Class SomeClass
    Public SomeProperty As String = 1.ToString()

    Shared Function Create()
        Return New SomeClass() With {
             .SomeProperty = .SomeProperty + NameOf(.SomeProperty)
        }
    End Function
End Class
```

I'll push a fix that covers a decent number of these cases
