### ISSUE TITLE
C# -> VB: Error converting ObjectCollectionInitializerSyntax within object initializer

### ISSUE THREAD

**Issue by ststeiger** [icsharpcode/CodeConverter#101]
https://roslyncodeconverter.azurewebsites.net/

C# => VB.NET 

Input:
```csharp
    using System.Collections.Generic;
    internal class SomeSettings
    {
        public IList<object> Converters { get; set; }
    }

    internal class Converter
    {
        public static readonly SomeSettings Settings = new SomeSettings
        {
            Converters = /* workaround: new[] */ {/* this initializer causes the invalid cast */},
        };
    }

```

Output:
```csharp
Error message:
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.ObjectCollectionInitializerSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax'.
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitAssignmentExpression(AssignmentExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitAssignmentExpression(AssignmentExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.<VisitInitializerExpression>b__83_3(ExpressionSyntax e)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__93`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitInitializerExpression(InitializerExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InitializerExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitInitializerExpression(InitializerExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InitializerExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertTopLevelExpression(ExpressionSyntax topLevelExpression)
   at ICSharpCode.CodeConverter.VB.CommonConversions.RemodelVariableDeclaration(VariableDeclarationSyntax declaration)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitFieldDeclaration(FieldDeclarationSyntax node)
```

Code Converter by https://github.com/icsharpcode/CodeConverter/ - Version 5.6.3.0

**Comment by GrahamTheCoder** [comment]
I've cut down the repro steps. I'll try to get a fix this weekend. 
Workaround in your code: before conversion put `new[]` in front of the collection initializer for JsonSerializerSettings.
