### ISSUE TITLE
VB -> C#: InvalidOperationException caused by LINQ GroupBy with multiple properties

### ISSUE THREAD

**Issue by CardenInsurance** [icsharpcode/CodeConverter#1014]
### VB.Net input code
```vbnet
Public Class ConversionTest4
    Private Class MyEntity
        Property FavoriteNumber As Integer
        Property FavoriteColor As String
        Property Name As String
    End Class
    Private Sub BugRepro()

        Dim entities As New List(Of MyEntity)

        Dim result As IEnumerable(Of String) = From e In entities
                                               Group e By e.FavoriteNumber, e.FavoriteColor Into g1 = Group
                                               Select g1.FirstOrDefault().Name

    End Sub
End Class
```

### Erroneous output
```C#
public class ConversionTest4
    {
        private class MyEntity
        {
            public int FavoriteNumber { get; set; }
            public string FavoriteColor { get; set; }
            public string Name { get; set; }
        }
        private void BugRepro()
        {

            var entities = new List<MyEntity>();

            var result = default
#error Cannot convert QueryExpressionSyntax - see comment for details
        /* Cannot convert QueryExpressionSyntax, System.InvalidOperationException: Sequence contains more than one element
            at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
            at ICSharpCode.CodeConverter.CSharp.QueryConverter.<ConvertSubQueryAsync>d__15.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at ICSharpCode.CodeConverter.CSharp.QueryConverter.<ConvertQueryWithContinuationAsync>d__14.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at ICSharpCode.CodeConverter.CSharp.QueryConverter.<ConvertQuerySegmentsAsync>d__12.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at ICSharpCode.CodeConverter.CSharp.QueryConverter.<ConvertClausesAsync>d__7.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.<VisitQueryExpression>d__68.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.<ConvertHandledAsync>d__8`1.MoveNext()

         Input:
         From e In entities
                                                        Group e By e.FavoriteNumber, e.FavoriteColor Into g1 = Group
                                                        Select g1.FirstOrDefault().Name

          */;

        }
    }
```

### Details
* Product in use: VS extension
* Version in use: 9.2.2.0
* This is a simplified repro code
* I believe this exception happens because the "Group e By" line contains multiple properties to group on.

**Comment by CardenInsurance** [comment]
I found a workaround for anyone who has this problem.  Before running the CodeConverter, refactor your VB code's "Group By" line to look like this.  Then, it'll convert to C# without errors.

```
Dim result As IEnumerable(Of String) = From e In entities
Group e By Key = New With {.FavoriteNumber = e.FavoriteNumber, .FavoriteColor = e.FavoriteColor} Into g1 = Group
Select g1.FirstOrDefault().Name
```
