### ISSUE TITLE
CONVERSION ERROR: usingKeyword in 'Global.System.[String]'

### ISSUE THREAD

**Issue by CSSenior** [icsharpcode/CodeConverter#1019]
### Steps to reproduce
1. get VisionXApiInterface.vb file
2. convert 
3. error is shown

### Error message shown

CONVERSION ERROR: usingKeyword in 'Global.System.[String]' at character 55
       at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken globalKeyword, SyntaxToken usingKeyword, SyntaxToken staticKeyword, SyntaxToken unsafeKeyword, NameEqualsSyntax alias, TypeSyntax namespaceOrType, SyntaxToken semicolonToken)
       at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken staticKeyword, NameEqualsSyntax alias, NameSyntax name)
       at ICSharpCode.CodeConverter.CSharp.DeclarationNodeVisitor.<VisitSimpleImportsClause>d__37.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.<ConvertHandledAsync>d__8`1.MoveNext()

**Comment by GrahamTheCoder** [comment]
Thanks for the report. The error message looks a bit odd, did any of it get cut off?
Could you share at least the first few lines of the file you are converting, and let me know whether you used the vs extension, website or command line?

**Comment by voroninp** [comment]
I am using an extension:

```
MediaViewServer\frmSettings.vb - conversion has errors: 
    CONVERSION ERROR: usingKeyword in 'Global.System.Configuration...' at character 8
       at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken globalKeyword, SyntaxToken usingKeyword, SyntaxToken staticKeyword, SyntaxToken unsafeKeyword, NameEqualsSyntax alias, TypeSyntax namespaceOrType, SyntaxToken semicolonToken)
       at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken staticKeyword, NameEqualsSyntax alias, NameSyntax name)
       at ICSharpCode.CodeConverter.CSharp.DeclarationNodeVisitor.<VisitSimpleImportsClause>d__37.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.<ConvertHandledAsync>d__8`1.MoveNext()
```


Here's the beginning of the file:

```
Imports System.Configuration.ConfigurationManager

Public Class frmSettings

    Private m_Vailid As Boolean = True
    Private m_Ok As Boolean = False
    Private m_UserName As String
    Private m_Password As String
    Private m_Domain As String

    Public ReadOnly Property OkClicked() As Boolean
        Get
            Return m_Ok
        End Get
    End Property

    Private Sub frmSettings_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim objConfig As Configuration.Configuration
            Dim objUserDoc As Xml.XmlDocument
            Dim objEncoder As System.Text.ASCIIEncoding
            Dim bytLicence As Byte()
            Dim intCount As Integer
            Dim strUncoded As String

            ' Open current configuration
            objConfig = Configuration.ConfigurationManager.OpenExeConfiguration(Application.ExecutablePath)
```

**Comment by GrahamTheCoder** [comment]
Thanks for the example. I can't reproduce the error with it in my environment.

Can you confirm the version of Visual Studio (and of the Code Converter extension)?

### Details

The weird thing about this error, is that it comes from within the Microsoft.CodeAnalysis library. It's an ArgumentException because the syntax kind of the usingKeyword parameter is wrong. But as you can see from the stack trace (and I've confirmed in the source), the code converter didn't pass that parameter, it was created within the library in an overload:
```csharp
       at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken globalKeyword, SyntaxToken usingKeyword, SyntaxToken staticKeyword, SyntaxToken unsafeKeyword, NameEqualsSyntax alias, TypeSyntax namespaceOrType, SyntaxToken semicolonToken)
       at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken staticKeyword, NameEqualsSyntax alias, NameSyntax name)
```

But this type of error in such a simple and common piece of generated code being released by Microsoft would be extremely unlikely.

**Comment by GrahamTheCoder** [comment]
I stand corrected. I have managed to repro on Version 17.7.0 Preview 2.0

Yes, I'm pretty sure Microsoft have released a bug. Thanks for bringing it to my attention since it will affect many users. I'll file it upstream and hope we can fix before this preview becomes the mainstream.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting the issue. I'll push out a code converter release with a workaround in the next day or two, and I've submitted PR https://github.com/dotnet/roslyn/pull/68762 upstream so that overload will be usable again in future versions.
