### ISSUE TITLE
C# -> VB: <![CDATA fails to convert to Raw String literal using https://converter.telerik.com/

### ISSUE THREAD

**Issue by JaieParker** [icsharpcode/CodeConverter#1032]
### Input code
```vbnet
Imports DevExpress.XtraRichEdit

Public class RichEditDocumentServerTest
  Inherits RichEditDocumentServer

  Public Function HasInnerServer() As Boolean
    Return InnerServer is Nothing
  End Function
End Class

Public class RichEditDocumentServerTestFix
    Inherits RichEditDocumentServer

    Public Function HasInnerServer() As Boolean
        Return InnerServer is Nothing
    End Function

    public Async Function SetHtmlText(htmlText As String) As Task(Of Integer)
		Dim count = 0
		While Not HasInnerServer()
			count += 1
			Await Task.Delay(10)
		End While
        Me.HtmlText = htmlText
		Return count
    End Function

End Class
<TestClass()> 
Public Class DocumentTests
  <TestInitialize()>
  Public Sub Init()
    'Log.AddDebug("Init Test")
  End Sub

  <TestMethod()> 
  Public Sub TestRichEditDocumentServerFix()
    Dim taskToRun = new List(Of Task(Of Boolean))
    For i As Integer = 0 To 1000
      taskToRun.Add(RichEditDocumentServerDataFix)
    Next  
    Dim result =  Task.WhenAll(taskToRun).Result
    Assert.IsTrue(result.All(Function (taskRun) taskRun = true))
  End Sub

  Async Function RichEditDocumentServerDataFix() As Task(Of Boolean)
    await Task.Delay(1)
    Dim processedHtml = <![CDATA[
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>
		
	</head>
	<body>
		<p class="cs95E872D0"><span class="cs9D249CCB">&nbsp;Regards,</span></p>
</body>
</html>
    ]]>.Value()
    Using server = New RichEditDocumentServer()
        server.HtmlText = processedHtml

      Dim m_emailBody = RichEditMailMessageExporter.GetEmailView(server)
      Dim m_originalText = server.Text
      Dim m_originalHtmlText = server.HtmlText
      Using srv2 = New RichEditDocumentServerTestFix
        If Not srv2.HasInnerServer()
            Debug.WriteLine("Proves issue is in RichEditDocumentServer for multi-threaded scenario")
        End If
        Dim count = await srv2.SetHtmlText(m_emailBody.EmailBody)
        Debug.WriteLine($"Count: {count}")
        Dim extratedText = srv2.Text
        If m_originalText.Length / 2 > extratedText.Length OrElse m_originalText.Trim().Length / 2 > extratedText.Trim().Length Then
            Debug.WriteLine($"m_emailBody.EmailBody: '{m_emailBody.EmailBody}', server.HtmlText: '{server.HtmlText}', extratedText: {extratedText}")
          Throw New Exception("Document body was set to string Empty")
        End If
      End Using
    End Using
      Return true
  End Function

  Public Sub TestRichEditDocumentServer()
      Dim taskToRun = new List(Of Task(Of Boolean))
      For i As Integer = 0 To 1000
          taskToRun.Add(RichEditDocumentServerData)
      Next  
      Dim result =  Task.WhenAll(taskToRun).Result
      Assert.IsTrue(result.All(Function (taskRun) taskRun = true))
  End Sub
End Class
```

### Erroneous output
```
/* Cannot convert LocalDeclarationStatementSyntax, CONVERSION ERROR: Conversion for XmlCDataSection not implemented, please report this issue in '<![CDATA[
 <!DOCTYPE html P...' at character 1220
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitXmlCDataSection(XmlCDataSectionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.XmlCDataSectionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitXmlCDataSection(XmlCDataSectionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.XmlCDataSectionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.ConvertInitializer(VariableDeclaratorSyntax declarator)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.SplitVariableDeclarations(VariableDeclaratorSyntax declarator)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.LocalDeclarationStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)
```

### Expected output

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/raw-string
I epect to see the raw string as per below or something equivalent
```csharp
var processedHtml = """""
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>
		
	</head>
	<body>
		<p class="cs95E872D0"><span class="cs9D249CCB">&nbsp;Regards,</span></p>
</body>
</html>
"""""
```

### Details
* Product in use: e.g. [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

Using the online tool: https://converter.telerik.com/

Cheers

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Confirmed still broken in the latest version. Probably a straightforward fix for the simple case at least, not sure if there are complex versions since I haven't seen it before!
