### ISSUE TITLE
VB -> C#: Cannot convert LocalDeclarationStatementSyntax, System.NullReferenceException

### ISSUE THREAD

**Issue by TymurGubayev** [icsharpcode/CodeConverter#1049]
### VB.Net input code
This one needs a bit of a setup, as it's related to the https://github.com/dotnet/roslyn/issues/68194.

First, we need a C# project with a ref return, f.e.
```cs
    public class MySpecialList<T>
    {
        private T dummy;
        public ref T this[int i]
        {
            get
            {
                return ref dummy;
            }
        }
    }
```

Then on the VB.NET side of things, we use that ref return in a with-statement like following.
```vbnet
Public Class LocalDeclConversionError
    Private Structure SomeStruct
        Dim SomeField As Integer
        Dim Text As String
    End Structure

    Dim lst As New CSProj.MySpecialList(Of SomeStruct)

    Sub S()
        Dim i As Integer
        Dim s As String

        With lst(i)
            .SomeField = 5
            s = .Text
        End With
    End Sub
End Class
```

### Erroneous output
Which results in `#error Cannot convert LocalDeclarationStatementSyntax - see comment for details`:

```C#
    public class LocalDeclConversionError
    {
        private struct SomeStruct
        {
            public int SomeField;
            public string Text;
        }

        private CSProj.MySpecialList<SomeStruct> lst = new CSProj.MySpecialList<SomeStruct>();

        public void S()
        {
            ;
#error Cannot convert LocalDeclarationStatementSyntax - see comment for details
            /* Cannot convert LocalDeclarationStatementSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
               at Microsoft.CodeAnalysis.VisualBasic.Symbol.get_CanBeReferencedByName()
               at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
               at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.Normalize(IEnumerable`1 data)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_DataFlowsIn()
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_Succeeded()
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.AnalyzeReadWrite()
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_ReadInside()
               at ICSharpCode.CodeConverter.CSharp.DefiniteAssignmentAnalyzer.IsDefinitelyAssignedBeforeRead(ISymbol localSymbol, DataFlowAnalysis methodFlow)
               at ICSharpCode.CodeConverter.CSharp.SemanticModelExtensions.IsDefinitelyAssignedBeforeRead(SemanticModel semanticModel, ISymbol locallyDeclaredSymbol, ModifiedIdentifierSyntax syntaxForSymbol)
               at ICSharpCode.CodeConverter.CSharp.CommonConversions.<ConvertEqualsValueClauseSyntaxAsync>d__36.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at ICSharpCode.CodeConverter.CSharp.CommonConversions.<SplitVariableDeclarationsAsync>d__34.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<SplitVariableDeclarationsAsync>d__62.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitLocalDeclarationStatement>d__32.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at ICSharpCode.CodeConverter.CSharp.PerScopeStateVisitorDecorator.<AddLocalVariablesAsync>d__6.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.<DefaultVisitInnerAsync>d__3.MoveNext()

            Input:
                    Dim i As Integer

             */
            ;

#error Cannot convert LocalDeclarationStatementSyntax - see comment for details
            /* Cannot convert LocalDeclarationStatementSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
                           at Microsoft.CodeAnalysis.VisualBasic.Symbol.get_CanBeReferencedByName()
                           at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
                           at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
                           at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.Normalize(IEnumerable`1 data)
                           at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_DataFlowsIn()
                           at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_Succeeded()
                           at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.AnalyzeReadWrite()
                           at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_ReadInside()
                           at ICSharpCode.CodeConverter.CSharp.DefiniteAssignmentAnalyzer.IsDefinitelyAssignedBeforeRead(ISymbol localSymbol, DataFlowAnalysis methodFlow)
                           at ICSharpCode.CodeConverter.CSharp.SemanticModelExtensions.IsDefinitelyAssignedBeforeRead(SemanticModel semanticModel, ISymbol locallyDeclaredSymbol, ModifiedIdentifierSyntax syntaxForSymbol)
                           at ICSharpCode.CodeConverter.CSharp.CommonConversions.<ConvertEqualsValueClauseSyntaxAsync>d__36.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at ICSharpCode.CodeConverter.CSharp.CommonConversions.<SplitVariableDeclarationsAsync>d__34.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<SplitVariableDeclarationsAsync>d__62.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitLocalDeclarationStatement>d__32.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at ICSharpCode.CodeConverter.CSharp.PerScopeStateVisitorDecorator.<AddLocalVariablesAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.<DefaultVisitInnerAsync>d__3.MoveNext()

                        Input:
                                Dim s As String

                         */
            {
                var withBlock = lst[i];
                withBlock.SomeField = 5;
                s = withBlock.Text;
            }
        }
    }
```

### Details
* Product in use: VS extension
* Version in use: ae25cdc920df68755fb233934028091c97b42853
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Stack trace looks likely to be another roslyn bug. May need fix upstream. Likely rare enough not to need a workaround.

**Comment by TymurGubayev** [comment]
stranger yet, there is another workaround: just access the property a second time...


```cs
System.Collections.Immutable.ImmutableArray<ISymbol> ri = default;
try
{
    ri = methodFlow.ReadInside;
}
catch
{
    ri = methodFlow.ReadInside;
}
```

I've created the issue in Roslyn: https://github.com/dotnet/roslyn/issues/71115.

**Comment by TymurGubayev** [comment]
Added a draft PR of how the solution might look like, but there is a problem with tests, please take a look at it.
