### ISSUE TITLE
vb -> c#: Cannot handle missing optional arguments 

### ISSUE THREAD

**Issue by RachelDavids** [icsharpcode/CodeConverter#114]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```vb
Imports System
Imports Mono.Cecil.Cil

Public Module MyExtensions

	public sub NewColumn(type As Type , Optional strV1 As String = nothing, optional code As Code = Code.Arglist)

	End sub

	public Sub CallNewColumn()
		NewColumn(GetType(MyExtensions))
		NewColumn(Nothing, ,code.Add)
		NewColumn(Nothing, "fred")

	End Sub
	
End Module
```

### Erroneous output
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic;
using Mono.Cecil.Cil;

public static class MyExtensions
{
    public static void NewColumn(Type type, string strV1 = null, Code code = Code.Arglist)
    {
    }

    public static void CallNewColumn()
    {
        NewColumn(typeof(MyExtensions));
        ;/* Cannot convert ExpressionStatementSyntax, CONVERSION ERROR: Conversion for OmittedArgument not implemented, please report this issue in '' at character 273
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitOmittedArgument(OmittedArgumentSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.OmittedArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitOmittedArgument(OmittedArgumentSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.OmittedArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitArgumentList>b__71_0(ArgumentSyntax a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitArgumentList(ArgumentListSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitArgumentList(ArgumentListSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitExpressionStatement(ExpressionStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
		NewColumn(Nothing, , code.Add)

 */		NewColumn(null/* TODO Change to default(_) if this is not a reference type */, "fred");
    }
}

```

### Possible Expected output
if the argument names are known then possibly the following would be acceptable.
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic;
using Mono.Cecil.Cil;

public static class MyExtensions
{
    public static void NewColumn(Type type, string strV1 = null, Code code = Code.Arglist)
    {
    }

    public static void CallNewColumn()
    {
        NewColumn(typeof(MyExtensions));
        NewColumn(null/* TODO Change to default(_) if this is not a reference type */, code: code.Add);
        NewColumn(null/* TODO Change to default(_) if this is not a reference type */, "fred");
    }
}

```

### Details
Web Converter
Version in use: e.g. 5.6.3

If the missing argument is eliminated, and named argument is used then the suggested output is returned.

**Comment by GrahamTheCoder** [comment]
Wow I didn't know that was allowed in VB! The alternative fix is to replace the omitted argument with the default value, but that would duplicate the value everywhere and be less like the original. So yep I think your solution is best. Thanks for the report!
