### ISSUE TITLE
C# -> VB: Conversion for LocalFunctionStatement not implemented

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#124]
### Input
```C#
namespace ICSharpCode.CodeConverter.CSharp
{
    public partial class VisualBasicConverter
    {
        class NodesVisitor : VBasic.VisualBasicSyntaxVisitor<CSharpSyntaxNode>
        {


            IEnumerable<MemberDeclarationSyntax> ConvertMembers(SyntaxList<VBSyntax.StatementSyntax> members)
            {
                IEnumerable<MemberDeclarationSyntax> ConvertMembersInner()
                {
                    foreach (var member in members)
                    {
                        yield return (MemberDeclarationSyntax) member.Accept(TriviaConvertingVisitor);

                        if (_additionalDeclarations.TryGetValue(member, out var additionalStatements))
                        {
                            _additionalDeclarations.Remove(member);
                            foreach (var additionalStatement in additionalStatements)
                            {
                                yield return additionalStatement;
                            }
                        }
                    }
                }

                var parentType = members.FirstOrDefault()?.GetAncestor<VBSyntax.TypeBlockSyntax>();
                _methodsWithHandles = GetMethodWithHandles(parentType);

                if (parentType == null || !_methodsWithHandles.Any()) {
                    return ConvertMembersInner();
                }

                return _additionalInitializers.WithAdditionalInitializers(ConvertMembersInner().ToList(), ConvertIdentifier(parentType.BlockStatement.Identifier));
            }

        }
    }
}
```

### Erroneous output
```vbnet
Namespace ICSharpCode.CodeConverter.CSharp
    Public Partial Class VisualBasicConverter
        Class NodesVisitor
            Inherits VBasic.VisualBasicSyntaxVisitor(Of CSharpSyntaxNode)

            Private Function ConvertMembers(ByVal members As SyntaxList(Of VBSyntax.StatementSyntax)) As IEnumerable(Of MemberDeclarationSyntax)
                Dim additionalStatements = Nothing
                                ' Cannot convert LocalFunctionStatementSyntax, CONVERSION ERROR: Conversion for LocalFunctionStatement not implemented, please report this issue in 'IEnumerable<MemberDeclarati...' at character 338
'    at ICSharpCode.CodeConverter.VB.MethodBodyVisitor.DefaultVisit(SyntaxNode node)
'    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
'    at Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
'    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
'    at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
'    at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)
' 
' Input: 
'                 IEnumerable<MemberDeclarationSyntax> ConvertMembersInner()
'                 {
'                     foreach (var member in members)
'                     {
'                         yield return (MemberDeclarationSyntax) member.Accept(TriviaConvertingVisitor);
' 
'                         if (_additionalDeclarations.TryGetValue(member, out var additionalStatements))
'                         {
'                             _additionalDeclarations.Remove(member);
'                             foreach (var additionalStatement in additionalStatements)
'                             {
'                                 yield return additionalStatement;
'                             }
'                         }
'                     }
'                 }
' 
' 
                Dim parentType = members.FirstOrDefault()?.GetAncestor(Of VBSyntax.TypeBlockSyntax)()
                _methodsWithHandles = GetMethodWithHandles(parentType)

                If parentType Is Nothing OrElse Not _methodsWithHandles.Any() Then
                    Return ConvertMembersInner()
                End If

                Return _additionalInitializers.WithAdditionalInitializers(ConvertMembersInner().ToList(), ConvertIdentifier(parentType.BlockStatement.Identifier))
            End Function
        End Class
    End Class
End Namespace
```

### Expected output
```vbnet
      Private Function ConvertMembers(ByVal members As SyntaxList(Of VBSyntax.StatementSyntax)) As IEnumerable(Of MemberDeclarationSyntax)

        Dim ConvertMembersInner = Iterator Function() As IEnumerable(Of MemberDeclarationSyntax)
                                    For Each member In members
                                      Yield CType(member.Accept(TriviaConvertingVisitor), MemberDeclarationSyntax)
                                      Dim additionalStatements As MemberDeclarationSyntax() = Nothing

                                      If _AdditionalDeclarations.TryGetValue(member, additionalStatements) Then
                                        _AdditionalDeclarations.Remove(member)

                                        For Each additionalStatement In additionalStatements
                                          Yield additionalStatement
                                        Next
                                      End If
                                    Next
                                  End Function

        Dim parentType = members.FirstOrDefault()?.GetAncestor(Of VBSyntax.TypeBlockSyntax)()
        _MethodsWithHandles = GetMethodWithHandles(parentType)

        If parentType Is Nothing OrElse Not _MethodsWithHandles.Any() Then
          Return ConvertMembersInner()
        End If

        Return _AdditionalInitializers.WithAdditionalInitializers(ConvertMembersInner().ToList(), ConvertIdentifier(parentType.BlockStatement.Identifier))
      End Function
```

**Comment by GrahamTheCoder** [comment]
See more minimal repro on #573

**Comment by GrahamTheCoder** [comment]
I'm imagining implementing this by adding byref parameters for any referenced locals.
This would cause a compile error where byref parameters aren't allowed (e.g. async, iterators), but would be a big improvement.
