### ISSUE TITLE
VB -> C#: Snippet not correctly detected

### ISSUE THREAD

**Issue by camainc** [icsharpcode/CodeConverter#126]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```VB

                    Dim cmccIds As New List(Of Integer)
                    For Each scr In _sponsorPayment.SponsorClaimRevisions
                        For Each claim In scr.Claims
                            If TypeOf claim.ClaimSummary Is ClaimSummary Then
                                With DirectCast(claim.ClaimSummary, ClaimSummary)
                                    cmccIds.AddRange(.UnpaidClaimMealCountCalculationsIds)
                                End With
                            End If
                        Next
                    Next


### Erroneous output
```vbnet
CONVERSION ERROR: Conversion for ForEachStatement not implemented, please report this issue in 'For Each scr In _sponsorPay...' at character 165
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitForEachStatement(ForEachStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ForEachStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitForEachStatement(ForEachStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ForEachStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<>c__DisplayClass27_0.<<ConvertMembers>g__ConvertMembersInner|0>d.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitClassBlock(ClassBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.WithPortedTrivia[TSource,TDest](SyntaxNode node, Func`3 portExtraTrivia)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.VisitClassBlock(ClassBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitCompilationUnit>b__24_3(StatementSyntax m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.ConvertCompilationTree(VisualBasicCompilation compilation, VisualBasicSyntaxTree tree)
   at ICSharpCode.CodeConverter.CSharp.VBToCSConversion.SingleFirstPass(Compilation sourceCompilation, SyntaxTree tree)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.SingleFirstPass(SyntaxTree tree, String treeFilePath)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.FirstPass()```
```

### Expected output
```vbnet
If relevant, the output you expected (in VB or C#), or a description of what you expected.
```

### Details
web converter

**Comment by GrahamTheCoder** [comment]
Workaround - surround the statements with a method:

```vbnet
    Public Sub SurroundingSub()
                    Dim cmccIds As New List(Of Integer)
                    For Each scr In _sponsorPayment.SponsorClaimRevisions
                        For Each claim In scr.Claims
                            If TypeOf claim.ClaimSummary Is ClaimSummary Then
                                With DirectCast(claim.ClaimSummary, ClaimSummary)
                                    cmccIds.AddRange(.UnpaidClaimMealCountCalculationsIds)
                                End With
                            End If
                        Next
                    Next
    End Sub
```

The converter tries to detect when the surrounding method/class is missing, but seems to be failing in this case. Thanks for the bug report!
