### ISSUE TITLE
VB -> C# Cannot convert LocalDeclarationStatementSyntax

### ISSUE THREAD

**Issue by camainc** [icsharpcode/CodeConverter#127]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```VB

Input: 
Dim _result =
                    From _claimProgramSummary In ClaimProgramSummaries
                    From _claimComponentSummary In _claimProgramSummary.ClaimComponentSummaries
                    From _lineItemCalculation In _claimComponentSummary.CurrentClaimLineItemCalculations
                    Select _lineItemCalculation

```

### Erroneous output
{
    ;/* Cannot convert LocalDeclarationStatementSyntax, System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.QueryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.QueryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.ConvertInitializer(VariableDeclaratorSyntax declarator)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.SplitVariableDeclarations(VariableDeclaratorSyntax declarator)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.LocalDeclarationStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
Dim _result =
                    From _claimProgramSummary In ClaimProgramSummaries
                    From _claimComponentSummary In _claimProgramSummary.ClaimComponentSummaries
                    From _lineItemCalculation In _claimComponentSummary.CurrentClaimLineItemCalculations
                    Select _lineItemCalculation

 */
}

```

### Details
web converter

**Comment by GrahamTheCoder** [comment]
Rolled into #29 to keep things together
Closing so there's just one place to track this
