### ISSUE TITLE
Cannot convert GroupBy clause without FunctionAggregationSyntax

### ISSUE THREAD

**Issue by camainc** [icsharpcode/CodeConverter#130]
### Input code
```VB
Public Function Reduce(ByVal accountEntries As IEnumerable(Of AccountEntry)) As IEnumerable(Of AccountEntry)
            Return (
                    From _accountEntry In accountEntries
                    Where _accountEntry.Amount > 0D
                    Group By _keys = New With
                                     {
                                         Key .LookupAccountEntryTypeId = _accountEntry.LookupAccountEntryTypeId,
                                         Key .LookupAccountEntrySourceId = _accountEntry.LookupAccountEntrySourceId,
                                         Key .SponsorId = _accountEntry.SponsorId,
                                         Key .LookupFundTypeId = _accountEntry.LookupFundTypeId,
                                         Key .StartDate = _accountEntry.StartDate,
                                         Key .SatisfiedDate = _accountEntry.SatisfiedDate,
                                         Key .InterestStartDate = _accountEntry.InterestStartDate,
                                         Key .ComputeInterestFlag = _accountEntry.ComputeInterestFlag,
                                         Key .SponsorClaimRevision = _accountEntry.SponsorClaimRevision
                                     } Into Group
                    Select New AccountEntry() With
                           {
                               .LookupAccountEntryTypeId = _keys.LookupAccountEntryTypeId,
                               .LookupAccountEntrySourceId = _keys.LookupAccountEntrySourceId,
                               .SponsorId = _keys.SponsorId,
                               .LookupFundTypeId = _keys.LookupFundTypeId,
                               .StartDate = _keys.StartDate,
                               .SatisfiedDate = _keys.SatisfiedDate,
                               .ComputeInterestFlag = _keys.ComputeInterestFlag,
                               .InterestStartDate = _keys.InterestStartDate,
                               .SponsorClaimRevision = _keys.SponsorClaimRevision,
                               .Amount = Group.Sum(Function(accountEntry) accountEntry.Amount),
                               .AccountTransactions = New List(Of AccountTransaction)(),
                               .AccountEntryClaimDetails = (From _accountEntry In Group From _claimDetail In _accountEntry.AccountEntryClaimDetails Select _claimDetail).Reduce().ToList
                           }
                 )
        End Function
```

### Erroneous output
```c#
 public IEnumerable<AccountEntry> Reduce(IEnumerable<AccountEntry> accountEntries)
    {
        ;/* Cannot convert ReturnStatementSyntax, System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.QueryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.QueryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitParenthesizedExpression(ParenthesizedExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParenthesizedExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitParenthesizedExpression(ParenthesizedExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParenthesizedExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitNamedFieldInitializer(NamedFieldInitializerSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamedFieldInitializerSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitNamedFieldInitializer(NamedFieldInitializerSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamedFieldInitializerSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitObjectMemberInitializer>b__89_0(FieldInitializerSyntax initializer)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__95`1.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitObjectMemberInitializer(ObjectMemberInitializerSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ObjectMemberInitializerSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitObjectMemberInitializer(ObjectMemberInitializerSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ObjectMemberInitializerSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ObjectCreationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ObjectCreationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.ConvertSelectClauseSyntax(SelectClauseSyntax vbFromClause)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.QueryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitQueryExpression(QueryExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.QueryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitParenthesizedExpression(ParenthesizedExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParenthesizedExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitParenthesizedExpression(ParenthesizedExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParenthesizedExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitReturnStatement(ReturnStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ReturnStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
            Return (
                    From _accountEntry In accountEntries
                    Where _accountEntry.Amount > 0D
                    Group By _keys = New With
                                     {
                                         Key .LookupAccountEntryTypeId = _accountEntry.LookupAccountEntryTypeId,
                                         Key .LookupAccountEntrySourceId = _accountEntry.LookupAccountEntrySourceId,
                                         Key .SponsorId = _accountEntry.SponsorId,
                                         Key .LookupFundTypeId = _accountEntry.LookupFundTypeId,
                                         Key .StartDate = _accountEntry.StartDate,
                                         Key .SatisfiedDate = _accountEntry.SatisfiedDate,
                                         Key .InterestStartDate = _accountEntry.InterestStartDate,
                                         Key .ComputeInterestFlag = _accountEntry.ComputeInterestFlag,
                                         Key .SponsorClaimRevision = _accountEntry.SponsorClaimRevision
                                     } Into Group
                    Select New AccountEntry() With
                           {
                               .LookupAccountEntryTypeId = _keys.LookupAccountEntryTypeId,
                               .LookupAccountEntrySourceId = _keys.LookupAccountEntrySourceId,
                               .SponsorId = _keys.SponsorId,
                               .LookupFundTypeId = _keys.LookupFundTypeId,
                               .StartDate = _keys.StartDate,
                               .SatisfiedDate = _keys.SatisfiedDate,
                               .ComputeInterestFlag = _keys.ComputeInterestFlag,
                               .InterestStartDate = _keys.InterestStartDate,
                               .SponsorClaimRevision = _keys.SponsorClaimRevision,
                               .Amount = Group.Sum(Function(accountEntry) accountEntry.Amount),
                               .AccountTransactions = New List(Of AccountTransaction)(),
                               .AccountEntryClaimDetails = (From _accountEntry In Group From _claimDetail In _accountEntry.AccountEntryClaimDetails Select _claimDetail).Reduce().ToList
                           }
                 )

 */
    }



```
### Details
web converter

**Comment by GrahamTheCoder** [comment]
I believe this specific case is now fixed
