### ISSUE TITLE
VB -> C#: Convert Date literals

### ISSUE THREAD

**Issue by kanonrai** [icsharpcode/CodeConverter#159]
### Input code
```vb
Public Function foo(Option ByVal date As Date = #1/1/1900#)
```

### Erroneous output
```CSharp
Error message:
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown.
Parameter name: value
Actual value was 1/1/1900 12:00:00 AM.
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.GetLiteralExpression(Object value, String valueText)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitLiteralExpression(LiteralExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
```

### Details
Product in use: vs extension

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report with minimal example. In most cases it'll be possible to do something like `DateTime.Parse("1/1/1900")`, but in the example you've given (and other similar ones requiring compile time constants - e.g. attributes) this will cause a problem. Would this be a reasonable solution:

```csharp
public int foo(DateTime? optionalDate = null)
{
    var date = optionalDate ?? DateTime.Parse("1/1/1900");
    // Rest of method body
}
```
