### ISSUE TITLE
VB -> C# Enum implicit cast

### ISSUE THREAD

**Issue by MarcusAndren2** [icsharpcode/CodeConverter#180]
### Input code
```vbnet
Public Enum TestEnum As Integer
    Test1 = 0
    Test2 = 1
End Enum

Dim t1 As Integer = TestEnum.Test1
```
### Erroneous output
```C#
int t1 = TestEnum.Test1;
```
### Expected output
```C#
int t1 = (int)TestEnum.Test1;
```
### Details
Product in use: VS Extension
Version in use: 6.0.0

In VB.Net, Enums have an implicit cast to their corresponding value type.

**Comment by GrahamTheCoder** [comment]
Good spot. Will need to test what other implicit casts exist, and whether it depends on the type the enum inherits from, so might take a while to get around to fixing this. Happy to accept a PR as ever. Thanks!

**Comment by jbstcyr** [comment]
It doesn't work going from C# ==> VB either.

The character position 298 is the beginning of the word
"int" on the first line of this code sample.
`   public enum CloakedStatus : int {
        Uncloaked = 0,
        ApplicationLevel = 0x0000001,
        ShellLevel = 0x0000002
}`
* Failure processing WindowsFormsAero\Dwm\CloakedStatus.cs
    CONVERSION ERROR: Conversion for SimpleBaseType not implemented, please report this issue in 'int' at character 298
       at ICSharpCode.CodeConverter.VB.NodesVisitor.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitSimpleBaseType(SimpleBaseTypeSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SimpleBaseTypeSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
       at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitSimpleBaseType(SimpleBaseTypeSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SimpleBaseTypeSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)

**Comment by mrmonday** [comment]
Related to #267.

**Comment by GrahamTheCoder** [comment]
Reopening because this case is still broken (assign enum to variable)
#### Input code
```vbnet
Public Enum TestEnum As Integer
    Test1 = 0
    Test2 = 1
End Enum

Dim EnumVariable = TestEnum.Test1 
Dim t1 As Integer = EnumVariable
```
#### Erroneous output
```C#
...
    private int t1 = EnumVariable;
...
```
#### Expected output
```C#
class SurroundingClass
{
    public enum TestEnum : int
    {
        Test1 = 0,
        Test2 = 1
    }

    private var EnumVariable = TestEnum.Test1;
    private int t1 = (int) EnumVariable;
}
```

The check for this case needs to cover anything of enum type, not just a direct reference to an enum
