### ISSUE TITLE
Solution/project tests broken in VS 15.8.6+

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#184]
See the project and solution tests. No cs or vb files get generated because no syntax trees are found in the loaded projects. 

This is almost certainly due to the changes to separate MSBuild from Visual Studio:
* https://github.com/dotnet/roslyn/issues/21583
* https://github.com/dotnet/roslyn/issues/21644
* https://github.com/neuecc/MessagePack-CSharp/issues/108

It doesn't affect nuget/web/vsix, but could affect other consumers who make use of MSBuild, so it may still get reported here.

**Comment by taylus** [comment]
It took me a while to get context on this, but once I did I was able to repro it nicely. I had an older version of VS2017 and updating it broke it like you said where the [project's syntax trees](https://github.com/icsharpcode/CodeConverter/blob/5b2749b8fb4014d802043fafb60b51699ec48cac/ICSharpCode.CodeConverter/Shared/ProjectConversion.cs#L88) were always an empty collection.

I was able to fix this in a throwaway console app by installing/updating the Microsoft.Build packages referenced in dotnet/roslyn#21644 to their latest versions (v15.9.20). Doing this in CodeConverter gets you the syntax trees back, but the [test I've been running](https://github.com/icsharpcode/CodeConverter/blob/5b2749b8fb4014d802043fafb60b51699ec48cac/Tests/CSharp/SolutionAndProjectTests.cs#L22) is failing on a difference in the Application.Designer.vb -> .cs file. The C# version is an empty namespace but the VB version is just some options which convert to nothing.

I was seeing this before I updated VS too, so it might be something that crept in while these tests were skipped. Any ideas?

![image](https://user-images.githubusercontent.com/8031544/49127407-c9377c00-f28c-11e8-8837-d4448844ad4e.png)

**Comment by taylus** [comment]
Here is a WIP: https://github.com/taylus/CodeConverter/tree/184-msbuild-update

**Comment by taylus** [comment]
Ok, I'll probably just tweak the actual or expected since an empty namespace declaration isn't much different from an empty file. I'll take another look tonight and then loop back around to your ideas in #210

**Comment by GrahamTheCoder** [comment]
Yes for now setting the expected to the actual is fine. These tests were intended to characterize the current behavior rather than being a perfect conversion. When reviewing the PR we should raise issues for any changes which look like regressions.

**Comment by taylus** [comment]
A little progress, I got the VB -> C# `ConvertSingleProject` test passing but `ConvertSolution` is blowing up with an exception converting the Resources.Designer.cs file. The actualText is a big ol' stack trace. Will see if I can figure out but may need your assistance.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.TryGetTypePromotedModuleSymbol(MemberAccessExpressionSyntax node, INamedTypeSymbol& moduleSymbol) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 1081
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 1060
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 1054
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 1054
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.ToAttributeArgument(ArgumentSyntax arg) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 1203
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitArgumentList(ArgumentListSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 1116
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitArgumentList(ArgumentListSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitAttribute(AttributeSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 90
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AttributeSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitAttribute(AttributeSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AttributeSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<ConvertAttribute>b__22_1(AttributeSyntax a) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 85
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitPropertyStatement(PropertyStatementSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 479
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitPropertyStatement(PropertyStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitPropertyBlock(PropertyBlockSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 493
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitPropertyBlock(PropertyBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<>c__DisplayClass29_0.<<ConvertMembers>g__ConvertMembersInner|0>d.MoveNext() in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 171
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitModuleBlock(ModuleBlockSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 225
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ModuleBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.WithPortedTrivia[TSource,TDest](SyntaxNode node, Func`3 portExtraTrivia) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 64
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.VisitModuleBlock(ModuleBlockSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 33
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ModuleBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitNamespaceBlock>b__28_0(StatementSyntax m) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 151
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitNamespaceBlock(NamespaceBlockSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 153
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamespaceBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitNamespaceBlock(NamespaceBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamespaceBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitCompilationUnit>b__24_3(StatementSyntax m) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 104
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ICSharpCode.CodeConverter.Util.EnumerableExtensions.ToReadOnlyCollection[T](IEnumerable`1 source) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\Util\EnumerableExtensions.cs:line 46
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 104
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitCompilationUnit(CompilationUnitSyntax node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 53
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.ConvertCompilationTree(VisualBasicCompilation compilation, VisualBasicSyntaxTree tree) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\VisualBasicConverter.cs:line 31
   at ICSharpCode.CodeConverter.CSharp.VBToCSConversion.SingleFirstPass(Compilation sourceCompilation, SyntaxTree tree) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\CSharp\VBToCSConversion.cs:line 34
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.SingleFirstPass(SyntaxTree tree, String treeFilePath) in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\Shared\ProjectConversion.cs:line 203
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.FirstPass() in D:\GitHub\CodeConverter\ICSharpCode.CodeConverter\Shared\ProjectConversion.cs:line 180
```

**Comment by GrahamTheCoder** [comment]
Good stuff. It's a "try" method, so it probably just needs an extra null check that returns false.
