### ISSUE TITLE
Error during conversion

### ISSUE THREAD

**Issue by InteXX** [icsharpcode/CodeConverter#19]
When attempting to convert from C#, I'm getting this exception:

    Selected C# code seems to have errors or to be incomplete:

    System.NotImplementedException: Microsoft.CodeAnalysis.CSharp.Syntax.IncompleteMemberSyntax not implemented!
       at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitIncompleteMember(IncompleteMemberSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.IncompleteMemberSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.<VisitCompilationUnit>b__14_1(MemberDeclarationSyntax m)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
       at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at ICSharpCode.CodeConverter.VB.CSharpConverter.Convert(CSharpSyntaxNode input, SemanticModel semanticModel, Document targetDocument)
       at ICSharpCode.CodeConverter.VB.CSharpConverter.ConvertText(String text, MetadataReference[] references)

Here's the code I'm trying to convert:

    Public Class TestClass
    {
        Public void TestMethod()
        {
            Console.WriteLine("This is a test.");
        }
    }

**Comment by siegfriedpammer** [comment]
The code you have written is syntactically wrong. In C# all keywords, i.e., `public`, `class`, etc. must be in lower case. So the correct code would look like:

```
public class TestClass
{
    public void TestMethod()
    {
        Console.WriteLine("This is a test.");
    }
}
```

**Comment by InteXX** [comment]
Damn that case sensitivity!  :-)

OK, thanks. It works now.
