### ISSUE TITLE
Make converter work for sub-method snippets

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#21]
Example code that should work
```
     If pType = "Dimension" Then
           Me.UsesDimensions = True
           Exit Sub
       End If
```
Expected output:
```
        if (pType == "Dimension")
        {
            this.UsesDimensions = true;
            return;
        }
```
Current behaviour: Throws 
```
Error message:
----- Exception 1 of 1 -----
System.NotImplementedException: Microsoft.CodeAnalysis.VisualBasic.Syntax.IfStatementSyntax not implemented!
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 64
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitIfStatement(IfStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.IfStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitCompilationUnit>b__12_1(StatementSyntax m) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 97
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 97
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.Convert(VisualBasicSyntaxNode input, SemanticModel semanticModel, Document targetDocument) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\VisualBasicConverter.cs:line 39
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.ConvertText(String text, MetadataReference[] references) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\VisualBasicConverter.cs:line 51
```

Example solution:
It works if you surround that code in a method and class, so we could just delegate the default visit of `NodesVisitor` to `MethodBodyVisitor`

**Comment by GrahamTheCoder** [comment]
This might also need a bit of tidying up of the split between the two visitors
