### ISSUE TITLE
C# -> VB: Snippet detection fails for field assignment expression

### ISSUE THREAD

**Issue by SezMe** [icsharpcode/CodeConverter#218]
### Input code

```csharp
this.DataContext = from task in tasks
    where task.Priority == pri
    select task;
```

### Erroneous output
No output.

### Details
web converter

Version in use:  6.2.0.0

```csharp
CONVERSION ERROR: Conversion for IncompleteMember not implemented, please report this issue in 'DataContext' at character 32
 at ICSharpCode.CodeConverter.VB.NodesVisitor.DefaultVisit(SyntaxNode node)
 at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
 at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
 at ICSharpCode.CodeConverter.VB.NodesVisitor.<VisitClassDeclaration>b__23_0(MemberDeclarationSyntax m)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
 at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
 at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
 at ICSharpCode.CodeConverter.VB.NodesVisitor.<VisitCompilationUnit>b__15_1(MemberDeclarationSyntax m)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
 at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
 at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
 at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
 at ICSharpCode.CodeConverter.VB.CSharpConverter.ConvertCompilationTree(CSharpCompilation compilation, CSharpSyntaxTree tree)
 at ICSharpCode.CodeConverter.VB.CSToVBConversion.SingleFirstPass(Compilation sourceCompilation, SyntaxTree tree)
 at ICSharpCode.CodeConverter.Shared.ProjectConversion.SingleFirstPass(SyntaxTree tree, String treeFilePath)
 at ICSharpCode.CodeConverter.Shared.ProjectConversion.FirstPass() 
```

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report. The converter is having trouble understanding the input. You can workaround this by surrounding it in a class/method:

```csharp
public class SurroundingClass
{
	public void SurroundingMethod()
	{
		this.DataContext = from task in tasks
			where task.Priority == pri
			select task;
	}
}
```

I see two things to be improved here:
* See if we can detect that this code needs a surrouding method/class before we pass it to Roslyn (some existing code detects other similar cases)
* Turn this type of exception into a more informative message saying something like "Not enough information to parse input. Try giving more context such as a surrounding method/class or using statements, and check the conversion direction is correct."
