### ISSUE TITLE
VB -> C#: Error (lot of comments about the issue) when define an array with number of elements

### ISSUE THREAD

**Issue by elGuille-MVP** [icsharpcode/CodeConverter#228]
Visual Basic:
```vbnet
Dim a(0 To colFics.Count - 1) As String
```

The expected conversion in C#:
```csharp
string[] a = new string[colFics.Count - 1];
```

The "(lot of comments about the issue)" are these:
```csharp
/* Cannot convert LocalDeclarationStatementSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.RangeArgumentSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax'.
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.<ConvertArrayBounds>b__20_0(ArgumentSyntax a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.ConvertArrayRankSpecifierSyntaxes(SyntaxList`1 arrayRankSpecifierSyntaxs, ArgumentListSyntax nodeArrayBounds, Boolean withSizes)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.AdjustFromName(TypeSyntax rawType, ModifiedIdentifierSyntax name, ExpressionSyntax initializer)
   at ICSharpCode.CodeConverter.CSharp.CommonConversions.SplitVariableDeclarations(VariableDeclaratorSyntax declarator)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.LocalDeclarationStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
            Dim a(0 To colFics.Count - 1) As String

 */
```

**Comment by GrahamTheCoder** [comment]
Thanks for reporting the error. I did not know about this syntax until now.

I have pushed a fix. Note that my implementation will produce:
```csharp
string[] a = new string[colFics.Count - 1 + 1];
```

I believe this is correct since Visual Basic specifies the final index of an array whereas C# specifies the length.

This fix will be released in the next couple of weeks, or you can of course use a development build. Thanks again!

**Comment by elGuille-MVP** [comment]
Or better is to use:
string[] a = new string[colFics.Count ];


But it's ok that way, thanks!
