### ISSUE TITLE
C# -> VB: Cannot convert: LeftShiftAssignmentExpression is not supported!

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [icsharpcode/CodeConverter#256]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```C#
public class Test
{
	public static void Main()
	{
		int x = 1;
		x <<= 1;
	}
}
```

### Erroneous output
```
Cannot convert ExpressionStatementSyntax, System.NotSupportedException: LeftShiftAssignmentExpression is not supported!
at ICSharpCode.CodeConverter.VB.SyntaxKindExtensions.ConvertToken(SyntaxKind t, TokenContext context)
at ICSharpCode.CodeConverter.VB.NodesVisitor.MakeAssignmentStatement(AssignmentExpressionSyntax node)
at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitAssignmentExpression(AssignmentExpressionSyntax node)
at Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitAssignmentExpression(AssignmentExpressionSyntax node)
at Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
at ICSharpCode.CodeConverter.VB.MethodBodyVisitor.ConvertSingleExpression(ExpressionSyntax node)
at ICSharpCode.CodeConverter.VB.MethodBodyVisitor.VisitExpressionStatement(ExpressionStatementSyntax node)
at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
	x <<= 1;

```

### Expected output
```vbnet
Public Class Test
    Public Shared Sub Main()
        Dim x As Integer = 1
	x <<= 1
    End Sub
End Class
```

### Details
Product in use: e.g. web converter / VS extension / both
Telerik Code Converter / Edit: ICSharpCode web Converter gives same error.

Version in use: e.g. 5.6.3
Telerik Code Converter doesn't mention the version it uses. / Edit: 6.6.0.0

Any other relevant information to the issue, or your interest in contributing a fix.

The following bit shift operators fail to convert:
```
<<
<<=
>>
>>=
```
Those operators use the same syntax in VB.NET, so it's strange it fails to convert.
Doing it VB -> C# works fine.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Even things that are exactly the same need explicit code to make the conversion work, so whether something works is more to do with how often it's used

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
You will have to do it yourself, I don't have VS2015+ installed.
