### ISSUE TITLE
VB -> C#: Conversion error with missing variable

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#259]
### Input code
```vbnet
Public Class Class1
    Sub Foo()
        For Me.Index = 0 To 10

        Next
    End Sub
End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Foo()
    {
        ;/* Cannot convert ForBlockSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitForBlock(ForBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ForBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
        For Me.Index = 0 To 10

        Next

 */
    }
}

```

### Expected output
```c#
public class Class1
{
    public void Foo()
    {
        for (var this.Index = 0; Index <= 10; Index++)
        {
        }
    }
}

```

### Details
Product in use: VS extension

Version in use: 6.6.0

The tool should be able to convert the for loop, even with the missing variable defintion.

**Comment by GrahamTheCoder** [comment]
Hopefully just a case of not dealing with member access expressions properly
