### ISSUE TITLE
VB -> C#: Error converting shared/static variable

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#260]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```vbnet
Public Class Class1
    Sub Foo()
        MyClass.Val = 6
    End Sub

    Shared Val As Integer
End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Foo()
    {
        ;/* Cannot convert AssignmentStatementSyntax, CONVERSION ERROR: Conversion for MyClassExpression not implemented, please report this issue in 'MyClass' at character 46
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMyClassExpression(MyClassExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MyClassExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMyClassExpression(MyClassExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MyClassExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitAssignmentStatement(AssignmentStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AssignmentStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

Input: 
        MyClass.Val = 6

 */
    }

    private static int Val;
}

```

### Expected output
```vbnet
public class Class1
{
    public void Foo()
    {
        Class1.Val = 6;
    }

    private static int Val;
}

```

### Details
Product in use: e.g. VS extension

Version in use: e.g. 6.6.0

**Comment by mrmonday** [comment]
I started working on this, but it's more complicated than it initially seems:

```vbnet
    <Fact()>
    Public Sub MyClassInheritance()
        Dim x As A = New B
        Assert.True(x.TestMethod())
    End Sub
 
    Public Class A
        Overridable Function F1() As Integer
            Return 1
        End Function
 
        Function F3() As Integer
            Return 3
        End Function
 
        Shared Property P1 As Integer
 
        Public Function TestMethod() As Boolean
            Return MyClass.F1() = 1 AndAlso MyClass.F3() = 3 AndAlso MyClass.P1 = 1
        End Function
    End Class
 
 
    Public Class B
        Inherits A
        Public Overrides Function F1() As Integer
            Return 11
        End Function
    End Class
```

The `MyClass.F3()` is the simplest case, this can become `this.F3() == 3`.

`MyClass.P1` is also simple, providing we have type info, it becomes `A.P1 == 1`. If we don't have type info I don't think we can convert it.

The `MyClass.F1()` case doesn't translate directly to C#, unless you introduce another non-virtual method to call.

**Comment by GrahamTheCoder** [comment]
I had never seen this syntax before. I think generating a non-virtual method seems like a sensible solution, though I'll happily accept a PR that handles the simpler cases and throws in the more complicated ones.
I'm assuming from that code block that you've discovered ExpressionTests.vb and the self verifying tests it creates, but if not, take a look.
