### ISSUE TITLE
VB -> C#: CBool() conversion incorrect

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#327]
### Input code
```vbnet
Imports System

Namespace ConsoleApp4
    Friend Class Program
        Public Shared Sub Main(ByVal args As String())
            Dim x As Object = "-1"
            Console.WriteLine(System.Convert.ToBoolean(x))
            Console.Read()
        End Sub
    End Class
End Namespace
```

Prints `True`.

IL:

```
	IL_0000: nop
	IL_0001: ldstr "-1"
	IL_0006: stloc.0
	IL_0007: ldloc.0
	IL_0008: call bool [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.Conversions::ToBoolean(object)
	IL_000d: call void [mscorlib]System.Console::WriteLine(bool)
	IL_0012: nop
	IL_0013: call int32 [mscorlib]System.Console::Read()
	IL_0018: pop
	IL_0019: ret
```

### Erroneous output

```c#
using System;

namespace ConsoleApp4
{
    namespace ConsoleApp4
    {
        internal class Program
        {
            public static void Main(string[] args)
            {
                object x = "-1";
                Console.WriteLine(System.Convert.ToBoolean(x));
                Console.Read();
            }
        }
    }
}
```

Which throws an exception:

```
System.FormatException
  HResult=0x80131537
  Message=String was not recognized as a valid Boolean.
  Source=mscorlib
  StackTrace:
   at System.Boolean.Parse(String value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ToBoolean(Object value)
   at ConsoleApp4.ConsoleApp4.Program.Main(String[] args) in C:\Users\robert.clipsham\source\repos\ConsoleApp4\ConsoleApp4\Program.cs:line 12
```

IL:

```
	IL_0000: nop
	IL_0001: ldstr "-1"
	IL_0006: stloc.0
	IL_0007: ldloc.0
	IL_0008: call bool [mscorlib]System.Convert::ToBoolean(object)
	IL_000d: call void [mscorlib]System.Console::WriteLine(bool)
	IL_0012: nop
	IL_0013: call int32 [mscorlib]System.Console::Read()
	IL_0018: pop
	IL_0019: ret
```

### Expected output
```c#
using System;

namespace ConsoleApp4
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            object x = "-1";
            Console.WriteLine(Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(x));
            Console.Read();
        }
    }
}
```

### Details

Product in use: VS extension

Version in use: 6.9.0.0

There seems to be a duplicate namespace produced too - looking at the IL, that might actually be correct, but I'm not sure it's expected behaviour. Should I open a bug for that?

**Comment by GrahamTheCoder** [comment]
Thanks! I believe the namespace issue is the one covered in https://github.com/icsharpcode/CodeConverter/issues/201

**Comment by GrahamTheCoder** [comment]
Consolidating
