### ISSUE TITLE
VB -> C#: Nullref in class with events

### ISSUE THREAD

**Issue by AngelSpeaks** [icsharpcode/CodeConverter#339]
I just joined GitHub.  I've just installed VS 2019 Community Edition and Code Converter. The application was developed using VS 2012 Express.  I right clicked on the solution name and selected VB to C# convert. It said 44 files were converted.

**Most of the files were not converted.  Here is an example showing the converter output.**
```csharp
namespace MyTalkingCommunicator
{
    class _failedMemberConversionMarker1
    {
    }
#error Cannot convert ClassBlockSyntax - see comment for details
    /* Cannot convert ClassBlockSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<>c.<GetMethodWithHandles>b__50_3(HandledEvent p)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<>c.<GetMethodWithHandles>b__50_1(IMethodSymbol m)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.GetMethodWithHandles(TypeBlockSyntax parentType)
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.ConvertMembers(SyntaxList`1 members)
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitClassBlock(ClassBlockSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.WithPortedTrivia[TSource,TDest](SyntaxNode node, Func`3 portExtraTrivia)
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.VisitClassBlock(ClassBlockSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.ConvertMember(StatementSyntax member)

    Input: 
    Public NotInheritable Class frmAbout
        'Copyright notice
        'Copyright © 2012 Angel Speaks Communication Products All Rights Reserved
        'Application Name:  Common
        'Author Name:       Cathy Finato for Angel Speaks Communications Products
        'Date:              July 2012
        '
        'Confidentiality notice
        'THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO CATHY FINATO (ANGELS PEAKS COMMUNICATIONS
        'PRODUCTS AND MAY NOT BE REPRODUCED, PUBLISHED, OR DISCLOSED TO OTHERS WITHOUT COMPANY
        'AUTHORIZATION.
        '
        Private intOrigHeight As Short = 415
        Private intOrigWidth As Short = 593
        Private blnResized As Boolean = True

        Private Sub frmAbout_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
            ' Set the title of the form.
            Me.lblTitle.Text = "Application Title: " & My.Application.Info.ProductName
            Me.lblDisclaimer.Text = "Warning.... " & My.Application.Info.Description
            Me.Text = "About " & My.Application.Info.ProductName
            Me.lblVersion.Text = String.Format("Version {0}", My.Application.Info.Version.ToString)
            Me.lblCopyright.Text = My.Application.Info.Copyright
            Me.lblCompany.Text = My.Application.Info.CompanyName
            Me.lblRegistration.Text = "Registration No: " & My.Settings.strRegistration
            Me.lblDescription.Text = "Application Description: " & My.Application.Info.Title

            blnResized = False                      'Controls when resize event runs

            'Set focus for help
            btnOK.Focus()

        End Sub

        Private Sub btnLicense_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnLicense.Click
            Dim frmLicense As New frmLicenseAgreement
            frmLicense.ShowDialog()
            Me.Close()
        End Sub

        Private Sub btnOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnOK.Click
            Me.Close()
        End Sub

        Private Sub frmAbout_SizeChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.SizeChanged
            If blnResized Then
                Exit Sub
            End If
            Call ResizeMe()
        End Sub

        Private Sub ResizeMe()
            'Resize controls when size of form changes
            Dim fSize As New SizeF((Me.Width / intOrigWidth), (Me.Height / intOrigHeight))
            Dim ctrLbl As Control

            For Each ctrLbl In Me.Controls
                ctrLbl.Scale(fSize)
            Next

            'Reset orig width
            intOrigWidth = Me.Width
            intOrigHeight = Me.Height
        End Sub

        Private Sub picHelp_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles picHelp.Click
            'Display help for this form
            Help.ShowHelp(Me, Me.hlpAbout.HelpNamespace, HelpNavigator.Topic, "About Angel Speaks.htm")

        End Sub
    End Class

     */
}
```
**I ran the original frmAbout.vb thru your web based conversion tool and got this:**
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

public sealed class frmAbout
{
    // Copyright notice
    // Copyright © 2012 Angel Speaks Communication Products All Rights Reserved
    // Application Name:  Common
    // Author Name:       Cathy Finato for Angel Speaks Communications Products
    // Date:              July 2012
    // 
    // Confidentiality notice
    // THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO CATHY FINATO (ANGELS PEAKS COMMUNICATIONS
    // PRODUCTS AND MAY NOT BE REPRODUCED, PUBLISHED, OR DISCLOSED TO OTHERS WITHOUT COMPANY
    // AUTHORIZATION.
    // 
    private short intOrigHeight = Conversions.ToShort(415);
    private short intOrigWidth = Conversions.ToShort(593);
    private bool blnResized = true;

    private void frmAbout_Load(System.Object sender, System.EventArgs e)
    {
        // Set the title of the form.
        this.lblTitle.Text = "Application Title: " + My.Application.Info.ProductName;
        this.lblDisclaimer.Text = "Warning.... " + My.Application.Info.Description;
        this.Text = "About " + My.Application.Info.ProductName;
        this.lblVersion.Text = string.Format("Version {0}", My.Application.Info.Version.ToString);
        this.lblCopyright.Text = My.Application.Info.Copyright;
        this.lblCompany.Text = My.Application.Info.CompanyName;
        this.lblRegistration.Text = "Registration No: " + My.Settings.strRegistration;
        this.lblDescription.Text = "Application Description: " + My.Application.Info.Title;

        blnResized = false;                      // Controls when resize event runs

        // Set focus for help
        btnOK.Focus();
    }

    private void btnLicense_Click(System.Object sender, System.EventArgs e)
    {
        frmLicenseAgreement frmLicense = new frmLicenseAgreement();
        frmLicense.ShowDialog();
        this.Close();
    }

    private void btnOK_Click(System.Object sender, System.EventArgs e)
    {
        this.Close();
    }

    private void frmAbout_SizeChanged(object sender, System.EventArgs e)
    {
        if (blnResized)
            return;
        ResizeMe();
    }

    private void ResizeMe()
    {
        // Resize controls when size of form changes
        SizeF fSize = new SizeF((this.Width / intOrigWidth), (this.Height / intOrigHeight));
        Control ctrLbl = default(Control);

        foreach (var ctrLbl in this.Controls)
            ctrLbl.Scale(fSize);

        // Reset orig width
        intOrigWidth = this.Width;
        intOrigHeight = this.Height;
    }

    private void picHelp_Click(System.Object sender, System.EventArgs e)
    {
        // Display help for this form
        Help.ShowHelp(this, this.hlpAbout.HelpNamespace, HelpNavigator.Topic, "About Angel Speaks.htm");
    }
}
```
**This is the original VB code:**
```vbnet
Public NotInheritable Class frmAbout
    'Copyright notice
    'Copyright © 2012 Angel Speaks Communication Products All Rights Reserved
    'Application Name:  Common
    'Author Name:       Cathy Finato for Angel Speaks Communications Products
    'Date:              July 2012
    '
    'Confidentiality notice
    'THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO CATHY FINATO (ANGELS PEAKS COMMUNICATIONS
    'PRODUCTS AND MAY NOT BE REPRODUCED, PUBLISHED, OR DISCLOSED TO OTHERS WITHOUT COMPANY
    'AUTHORIZATION.
    '
    Private intOrigHeight As Short = 415
    Private intOrigWidth As Short = 593
    Private blnResized As Boolean = True

    Private Sub frmAbout_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        ' Set the title of the form.
        Me.lblTitle.Text = "Application Title: " & My.Application.Info.ProductName
        Me.lblDisclaimer.Text = "Warning.... " & My.Application.Info.Description
        Me.Text = "About " & My.Application.Info.ProductName
        Me.lblVersion.Text = String.Format("Version {0}", My.Application.Info.Version.ToString)
        Me.lblCopyright.Text = My.Application.Info.Copyright
        Me.lblCompany.Text = My.Application.Info.CompanyName
        Me.lblRegistration.Text = "Registration No: " & My.Settings.strRegistration
        Me.lblDescription.Text = "Application Description: " & My.Application.Info.Title

        blnResized = False                      'Controls when resize event runs

        'Set focus for help
        btnOK.Focus()

    End Sub

    Private Sub btnLicense_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnLicense.Click
        Dim frmLicense As New frmLicenseAgreement
        frmLicense.ShowDialog()
        Me.Close()
    End Sub

    Private Sub btnOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnOK.Click
        Me.Close()
    End Sub

    Private Sub frmAbout_SizeChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.SizeChanged
        If blnResized Then
            Exit Sub
        End If
        Call ResizeMe()
    End Sub

    Private Sub ResizeMe()
        'Resize controls when size of form changes
        Dim fSize As New SizeF((Me.Width / intOrigWidth), (Me.Height / intOrigHeight))
        Dim ctrLbl As Control

        For Each ctrLbl In Me.Controls
            ctrLbl.Scale(fSize)
        Next

        'Reset orig width
        intOrigWidth = Me.Width
        intOrigHeight = Me.Height
    End Sub

    Private Sub picHelp_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles picHelp.Click
        'Display help for this form
        Help.ShowHelp(Me, Me.hlpAbout.HelpNamespace, HelpNavigator.Topic, "About Angel Speaks.htm")

    End Sub
End Class
```
Thank you for any assistance.

**Comment by GrahamTheCoder** [comment]
Hi, thanks for getting involved in the project and raising this! I'm pretty sure I know what the issue is - it relates to handling form events e.g. `Handles Me.SizeChanged`.
The reason it works on the web converter is because you're only converting one file, so it doesn't understand those event handlers since the other part of the partial class isn't present.

I'll try to get a fix out in the next few days. In the meantime as a workaround you could try removing things like ` Handles Me.SizeChanged` and `Handles MyClass...` and `Handles MyBase...` and retry the conversion (though obviously you'll need to then add back those event signups yourself.

**Comment by GrahamTheCoder** [comment]
Actually, would you mind trying this beta version - it should handle `Me` and `MyBase`:
https://github.com/icsharpcode/CodeConverter/releases/tag/6.9.5

**Comment by AngelSpeaks** [comment]
Graham, thank you for your prompt response.  I will give the beta version a try.

**Comment by AngelSpeaks** [comment]
Graham, I got the attached after installing.

![image](https://user-images.githubusercontent.com/53458637/62150401-87e7e800-b2c3-11e9-8fb5-a6def9c74a1f.png)

**Comment by AngelSpeaks** [comment]
![image](https://user-images.githubusercontent.com/53458637/62150462-abab2e00-b2c3-11e9-814a-00b55fd780f0.png)

**Comment by GrahamTheCoder** [comment]
Ah sorry, no need to build it yourself, just download the vsix and run it to install the built version (under assets on that link). Here's a direct link https://github.com/icsharpcode/CodeConverter/releases/download/6.9.5/CodeConverter.VsExtension.vsix

**Comment by AngelSpeaks** [comment]
Thanks. I'm so new to this.  I should have guessed that you wouldn't want me to build it.

**Comment by AngelSpeaks** [comment]
Status: ran the beta version. 266 errors.  It will take awhile to go thru these.  I will keep you posted.

![image](https://user-images.githubusercontent.com/53458637/62159396-4103ed80-b2d7-11e9-89c2-27f3cae1446f.png)

**Comment by GrahamTheCoder** [comment]
No worries. Building the converter yourself would have also been fine - in theory it should build straightaway for everyone straight after cloning. I was just trying to save you some effort.

It looks like the errors visible relate to #136 
It's a big job to fix that issue in the converter so it's unlikely to be fixed for a few months.

I'll rename this issue to relate to the first problem you found. Feel free to open issues for other specific bits. Let me know on this issue if you see any other problems with events (that aren't related to the 'My' name space)

**Comment by AngelSpeaks** [comment]
Thanks Graham.
