### ISSUE TITLE
Tests using MSBuildWorkspace are flaky

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#376]
The MSBuildWorkspace (only used in 4 tests) occasionally sees two different issues. A NullReferenceException, and (more rarely) this one:

```csharp
CodeConverter.Tests.VB.SolutionAndProjectTests.ConvertSingleProject [FAIL]
      System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
      Stack Trace:
           at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
           at System.Reflection.RuntimeAssembly.get_DefinedTypes()
           at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
           at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
           at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
           at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
           at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
           at Microsoft.CodeAnalysis.Host.Mef.MSBuildMefHostServices.get_DefaultServices()
           at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create(IDictionary`2 properties)
        Tests\TestRunners\MsBuildFixture.cs(114,0): at CodeConverter.Tests.TestRunners.MsBuildFixture.CreateWorkspaceUnhandled()
        Tests\TestRunners\MsBuildFixture.cs(104,0): at CodeConverter.Tests.TestRunners.MsBuildFixture.CreateWorkspace()
           at System.Lazy`1.CreateValue()
           at System.Lazy`1.LazyInitValue()
           at System.Lazy`1.get_Value()
        Tests\TestRunners\MsBuildFixture.cs(58,0): at CodeConverter.Tests.TestRunners.MsBuildFixture.<GetSolutionAsync>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
           at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_1.<<GetValueAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        Tests\TestRunners\MsBuildFixture.cs(74,0): at CodeConverter.Tests.TestRunners.MsBuildFixture.<ConvertProjectsWhere>d__10`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        Tests\VB\SolutionAndProjectTests.cs(27,0): at CodeConverter.Tests.VB.SolutionAndProjectTests.<ConvertSingleProject>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

We should see if we can upgrade to a later version that fixes the issue

I believe the nullref in optionsservice is some kind of multiple initialization issue (possible a multithreading issue)

Could be related to https://github.com/dotnet/roslyn/issues/17401 though that doesn't mention the flakiness seen here

**Comment by GrahamTheCoder** [comment]
Pretty sure all the issues here come down to:
https://github.com/dotnet/roslyn/pull/40574#discussion_r422064812

**Comment by sharwell** [comment]
You need to construct MSBuildWorkspace using vs-mef. Here's an example:
https://github.com/dotnet/roslyn-sdk/blob/11a4dc4e7b5ac2e1d3cce7cf5533cb51b295df64/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L1211-L1216

Absent that, you must ensure that the tests using MSBuildWorkspace do not run in parallel. The default MEF container does not support parallel use _even across two completely separate instances_.

**Comment by GrahamTheCoder** [comment]
Thanks 😄  I was thinking that, but definitely appreciate the confirmation since copying ~150 lines of code just to get a thread safe constructor was triggering alarm bells! (the referenced block, the export provider construction, and the contents of ExportProviderExtensions).
