### ISSUE TITLE
Simple if statement

### ISSUE THREAD

**Issue by mzshari** [icsharpcode/CodeConverter#389]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
 If UserName <> SchemaOwner Then
                            CFGDictionarySimple = Replace(GetStringValue(oRecordset, "CFGDictionarySimple"), "&user.", UserName)
                            CFGDictionarySimple = Replace(CFGDictionarySimple, "&USER.", UserName)
                        Else
                            CFGDictionarySimple = Replace(GetStringValue(oRecordset, "CFGDictionarySimple"), "&user..", " ")
                            CFGDictionarySimple = Replace(CFGDictionarySimple, "&USER..", " ")
                        End If
```

### Erroneous output

Error converting code
Error message:
CONVERSION ERROR: Conversion for IfStatement not implemented, please report this issue in 'If UserName <> SchemaOwner ...' at character 0
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitIfStatement(IfStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.IfStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitIfStatement(IfStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.IfStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<VisitCompilationUnit>b__24_3(StatementSyntax m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.ConvertCompilationTree(VisualBasicCompilation compilation, VisualBasicSyntaxTree tree)
   at ICSharpCode.CodeConverter.CSharp.VBToCSConversion.SingleFirstPass(Compilation sourceCompilation, SyntaxTree tree)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.SingleFirstPass(SyntaxTree tree, String treeFilePath)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.FirstPass()

**Comment by GrahamTheCoder** [comment]
Thanks for getting in touch. It looks like you're using an old version of the converter. If I put your input straight into the latest release it gives an attempted conversion: https://codeconverter.icsharpcode.net/

Remember, the more context you give the converter, the more it will get right, if you use the [Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter) within a buildable project you'll get the best results.

If you're seeing this on a recent version, please reopen and add a bit more information, I'll close this for now.
