### ISSUE TITLE
C# -> VB: "is null" crashes conversion

### ISSUE THREAD

**Issue by HugoRoss** [icsharpcode/CodeConverter#427]
### Input code
```C#
public class Test {

    public bool Foo {
        get {
	    return (Bar is null); //Crashes conversion to VB
        }
    }

    public string Bar { get; private set; }

}
```

### Erroneous output
```vbnet
Error converting code
Error message:
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown.
Parameter name: p
Actual value was null.
   at ICSharpCode.CodeConverter.VB.CommonConversions.<>c.<ConvertToVariableDeclarator>b__10_1(PatternSyntax p)
   at ICSharpCode.CodeConverter.Util.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 defaultFunc)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertToVariableDeclarator(IsPatternExpressionSyntax node)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertToDeclarationStatement(List`1 des, List`1 isPatternExpressions)
   at ICSharpCode.CodeConverter.VB.CommonConversions.InsertRequiredDeclarations(SyntaxList`1 convertedStatements, CSharpSyntaxNode originaNode)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertStatement(StatementSyntax statement, CSharpSyntaxVisitor`1 methodBodyVisitor)
   at ICSharpCode.CodeConverter.VB.CommonConversions.<>c__DisplayClass5_0.<ConvertStatements>b__0(StatementSyntax s)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertStatements(SyntaxList`1 statements, MethodBodyVisitor iteratorState)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertBody(BlockSyntax body, ArrowExpressionClauseSyntax expressionBody, MethodBodyVisitor iteratorState)
   at ICSharpCode.CodeConverter.VB.CommonConversions.ConvertAccessor(AccessorDeclarationSyntax node, Boolean& isIterator)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.ConvertPropertyBlock(BasePropertyDeclarationSyntax node, SyntaxToken id, SyntaxTokenList modifiers, ParameterListSyntax parameterListSyntax, ArrowExpressionClauseSyntax arrowExpressionClauseSyntax, EqualsValueSyntax initializerOrNull)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitPropertyDeclaration(PropertyDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitPropertyDeclaration(PropertyDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.<VisitClassDeclaration>b__23_0(MemberDeclarationSyntax m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.<VisitCompilationUnit>b__15_1(MemberDeclarationSyntax m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.ConvertCompilationTree(CSharpCompilation compilation, CSharpSyntaxTree tree)
   at ICSharpCode.CodeConverter.VB.CSToVBConversion.SingleFirstPass(Compilation sourceCompilation, SyntaxTree tree)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.SingleFirstPass(SyntaxTree tree, String treeFilePath)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.FirstPass()
```

### Expected output
```vbnet
Public Class Test
    Public ReadOnly Property Foo As Boolean
        Get
            Return (Bar Is Nothing)
        End Get
    End Property

    Public Property Bar As String
End Class
```

### Details
* Telerik conversion website (~http://converter.telerik.com/~)

**Comment by GrahamTheCoder** [comment]
Thanks for the repro Hugo. It still fails on the latest version here https://codeconverter.icsharpcode.net/ too
Since there's a stacktrace, it's just a case of adding the test case to ExpressionTests, then running in debug mode and seeing the state where things go wrong.  Should be reasonably straightforward fix too - let me know if you are you interested in having a go and want any help, otherwise I'll try to get around to it soonish

**Comment by HugoRoss** [comment]
Hello Graham

Although I have some experience in code conversion (I have written once a
Jscript.net to C# translator) I haven't had a look yet at the source of
this code converter and am not sure how long it would take me to get into
it. So I think I leave this fix to you if you don't mind (except if you
fancy a pair programming session - that would save me the work-in overhead).

Best regards
Christoph

Am So., 17. Nov. 2019 um 10:48 Uhr schrieb GrahamTheCoder <
notifications@github.com>:

**Comment by GrahamTheCoder** [comment]
In general I'm up for a pairing session on something if you're interested in getting involved. It's just a case of finding time and coordinating. Let me know if you see something you're enthusiastic to pair on.

**Comment by HugoRoss** [comment]
@GrahamTheCoder: I also noticed that VB.NETs XML language support throws exceptions when converted to C#, maybe that would be something? What time zone are you in? I am in UTC+1...

**Comment by GrahamTheCoder** [comment]
Cool, yeah it could be a slightly large issue, but let's try to find a good first slice of it. I'm in UTC - drop me an email on grahamthecoder@gmail.com with when you're free. Probably 8th-10th of December are good options
