### ISSUE TITLE
VB -> C#: Call to function without bracket

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#446]
### Input code
```vbnet
Call mySuperFunction
```

### Erroneous output
```C#
{
    ;
#error Cannot convert CallStatementSyntax - see comment for details
    /* Cannot convert CallStatementSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
       at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.ProbablyNotAMethodCall(InvocationExpressionSyntax node, ISymbol symbol, ITypeSymbol symbolReturnType) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 1162
       at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.<>c__DisplayClass66_0.<<VisitInvocationExpression>g__ConvertInvocationSubExpression|0>d.MoveNext() in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 711
    --- End of stack trace from previous location where exception was thrown ---
       at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitInvocationExpression(InvocationExpressionSyntax node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 726
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper`1.Visit(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 23
       at ICSharpCode.CodeConverter.CSharp.SyntaxNodeVisitorExtensions.AcceptAsync[T](SyntaxNode node, CommentConvertingVisitorWrapper`1 visitorWrapper) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\SyntaxNodeVisitorExtensions.cs:line 17
       at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.VisitCallStatement(CallStatementSyntax node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\MethodBodyExecutableStatementVisitor.cs:line 743
       at ICSharpCode.CodeConverter.CSharp.ByRefParameterVisitor.CreateLocals(VisualBasicSyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ByRefParameterVisitor.cs:line 53
       at ICSharpCode.CodeConverter.CSharp.ByRefParameterVisitor.AddLocalVariables(VisualBasicSyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ByRefParameterVisitor.cs:line 49
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingMethodBodyVisitor.cs:line 44
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingMethodBodyVisitor.cs:line 35

    Input:
    Call mySuperFunction

     */
}
```

### Expected output
```C#
{
    mySuperFunction();
}
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.3.0.0
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report! It's now fixed on master which will hopefully be released in the next couple of weeks.
