### ISSUE TITLE
VB -> C#: ReDim with missing semantic info

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#501]
### Input code
```vbnet
ReDim Preserve Tablica[intNowyRozmiar]
```

### Erroneous output
```C#
{
    ;
#error Cannot convert ReDimStatementSyntax - see comment for details
    /* Cannot convert ReDimStatementSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Symbols.ErrorTypeSymbol' to type 'Microsoft.CodeAnalysis.IArrayTypeSymbol'.
       at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.CreateNewArrayAssignment(ExpressionSyntax vbArrayExpression, ExpressionSyntax csArrayExpression, List`1 convertedBounds, Int32 nodeSpanStart) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\MethodBodyExecutableStatementVisitor.cs:line 313
       at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.ConvertRedimClause(RedimClauseSyntax node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\MethodBodyExecutableStatementVisitor.cs:line 208
       at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitReDimStatement>b__35_0(RedimClauseSyntax arrayExpression) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\MethodBodyExecutableStatementVisitor.cs:line 194
       at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions.SelectAsync[TArg,TResult](IEnumerable`1 source, Func`2 selector)
       at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions.SelectManyAsync[TArg,TResult](IEnumerable`1 nodes, Func`2 selector) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\Shared\AsyncEnumerableTaskExtensions.cs:line 23
       at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.VisitReDimStatement(ReDimStatementSyntax node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\MethodBodyExecutableStatementVisitor.cs:line 194
       at ICSharpCode.CodeConverter.CSharp.ByRefParameterVisitor.CreateLocals(VisualBasicSyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ByRefParameterVisitor.cs:line 53
       at ICSharpCode.CodeConverter.CSharp.ByRefParameterVisitor.AddLocalVariables(VisualBasicSyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\ByRefParameterVisitor.cs:line 43
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingMethodBodyVisitor.cs:line 39
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingMethodBodyVisitor.cs:line 29

    Input:
    ReDim Preserve Tablica[intNowyRozmiar]

     */
}
```

### Expected output
```C#
Array.Resize(ref Tablica, intNowyRozmiar)
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.6.0.0
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
I didn't know about the Array.Resize method, so that could possibly simplify the redim code in general.

I believe the input is too ambiguous to get the correct conversion in all cases (impossible to resolve the array type or rank) but I'm happy to accept a PR that defaults to Array.Resize when the symbol info isn't known (see the `ConvertRedimClause` method) since I think the code+compilation error it'd cause for 2d arrays would make it clear what needs doing to fix it without looking back at the source code.

```csharp
        int[,] Tablica = new int[3,4];
        // CS0411 The type arguments for method 'Array.Resize<T>(ref T[], int)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
        Array.Resize(ref Tablica, 4);
```
