### ISSUE TITLE
C# -> VB: after updating VS2019 to 16.4.5 its not working at all anymore

### ISSUE THREAD

**Issue by Hefaistos68** [icsharpcode/CodeConverter#534]
Getting only the following exception for any conversion attempt:
---------------------------
Code converter
---------------------------
An error has occured during conversion: System.ArgumentException: SyntaxTree is not part of the compilation

Parameter name: syntaxTree

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)

   at ICSharpCode.CodeConverter.VB.CaseConflictResolver.<>c__DisplayClass2_0.<GetLocalSymbolSets>b__1(SyntaxTree sourceTree)

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at ICSharpCode.CodeConverter.VB.CaseConflictResolver.<RenameClashingSymbols>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VB.CSToVBProjectContentsConverter.<InitializeSourceAsync>d__16.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VB.CSToVBConversion.<CreateProjectContentsConverter>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.Shared.ProjectConversion.<ConvertSingle>d__8`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at CodeConverter.VsExtension.CodeConversion.<ConvertDocumentUnhandledAsync>d__23`1.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\CodeConversion.cs:line 233

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass14_0`1.<<PerformDocumentConversionAsync>b__0>d.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\CodeConversion.cs:line 63

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at CodeConverter.VsExtension.CodeConversion.<PerformDocumentConversionAsync>d__14`1.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\CodeConversion.cs:line 62

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at CodeConverter.VsExtension.ConvertCSToVBCommand.<ConvertDocumentAsync>d__24.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\ConvertCSToVBCommand.cs:line 186
---------------------------
OK   
---------------------------

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension 
* Version in use: 7.8
* Did you see it working in a previous version, which? any VS2019 prior to 16.4.5

**Comment by GrahamTheCoder** [comment]
Hi, thanks for posting. I'm glad to say that this is fixed (known as #527). The release will come out in the next day or so, or you can use the latest [CI build](https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=934&view=artifacts&type=publishedArtifacts) if you're in a rush
