### ISSUE TITLE
VS2017 conversion show big error message

### ISSUE THREAD

**Issue by Rado8267** [icsharpcode/CodeConverter#563]
I have installed newest version of converter in VS 2017 Enterprise. If I want convert VB.NET code to C# I get this error message:
```
---------------------------
Code converter
---------------------------
An error has occured during conversion - press Ctrl+C to copy the details: System.MissingMethodException: Method not found: 'Void System.Threading.Tasks.Dataflow.DataflowBlockOptions.set_EnsureOrdered(Boolean)'.
   at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions.<ParallelSelectAwait>d__1`2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.MoveNext[TStateMachine](TStateMachine& stateMachine)
   at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions.<ParallelSelectAwait>d__1`2.System.IAsyncDisposable.DisposeAsync()
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.<Convert>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.<Convert>d__19.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.<ConvertSingle>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentUnhandledAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass15_0`1.<<ConvertDocumentAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<ConvertDocumentAsync>d__24.MoveNext()
---------------------------
OK   
---------------------------
```
Output window:
Converting XXXXX.aspx.vb...

Phase 1 of 2:

That is all. Can you help me?

**Comment by dreamworks** [comment]
same issue here... are we missing some core dlls?

**Comment by GrahamTheCoder** [comment]
Hi, thanks for posting. It looks like a dependency upgrade in a recent release broke support for VS2017 - I can reproduce this issue on VisualStudio.15.Release/15.9.21+28307.1064

For now, you'll need to either use VS2019, or uninstall the extension, close all visual studio windows, then install version [8.01 from here](https://github.com/icsharpcode/CodeConverter/releases/tag/8.0.1)

If there's any reason you can't use VS2019 I'd be interested to know why (is it a licensing thing?) since I'll be considering dropping support for VS2017 in 6 months

**Comment by dreamworks** [comment]
Hi,

the solution I was trying to use it, is "technically super-outdated" with a big mess of c# and vb projects, old node.js modules and such. Classic entropy death scenario,.  Issue is, the solution just doesn't compile/work under vs2019 and "upgrading" is just too much of an effort..
Licenses issues are not the case, but the use-case for those kind of "refactoring tools" are IMHO mainly quite old (and mostly messy) solutions, where you don't really want to "touch" the overall build process and mess around with upgrading to a newer VS release. just my 5 cents on it...

**Comment by GrahamTheCoder** [comment]
Makes sense, thanks for the info. I would like to keep VS2017 going as long as possible for the reason you describe, but it's pretty hard to stay compatible while making use of the great new tools available.

I've put in a tentative fix, would you mind trying it? There's a CI build artifact you can try here: https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=1188&view=results
Again, uninstall the extension, close all VS windows, then install the vsix from the "published artifact"

**Comment by dreamworks** [comment]
it's working now under vs2017.. thx a lot!

**Comment by GrahamTheCoder** [comment]
Great thanks for confirming!

**Comment by Rado8267** [comment]
It's working, Thank you :)
