### ISSUE TITLE
C# -> VB: Local function conversion failure

### ISSUE THREAD

**Issue by carlossanlop** [icsharpcode/CodeConverter#573]
### Input code
```csharp
class C
{
    void M()
    {
        void LocalMethod()
        {
            OtherMethod();
        }
        LocalMethod();
    }
    void OtherMethod(){}
}
```

### Erroneous output
```vbnet
Class C
    Private Sub M()
                ''' Cannot convert LocalFunctionStatementSyntax, CONVERSION ERROR: Conversion for LocalFunctionStatement not implemented, please report this issue in 'void LocalMethod()
  {
   O...' at character 37
'''    at ICSharpCode.CodeConverter.VB.MethodBodyVisitor.DefaultVisit(SyntaxNode node)
'''    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
'''    at Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
'''    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
'''    at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
'''    at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)
''' 
''' Input: 
'''         void LocalMethod()
        {
            OtherMethod();
        }

''' 
        LocalMethod()
    End Sub

    Private Sub OtherMethod()
    End Sub
End Class

```

### Details
* Product in use: e.g. https://converter.telerik.com/
* Version in use: what you show in that URL as of today
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Hi, thanks for the bug report. I'm going to consolidate it with https://github.com/icsharpcode/CodeConverter/issues/124, please do give that issue a thumbs up to indicate your support for it. Thanks!
