### ISSUE TITLE
Vs 16.7 error bar

### ISSUE THREAD

**Issue by billpeet** [icsharpcode/CodeConverter#586]
### Steps to reproduce
1. Use VS 2019 to create a brand new VB.NET Framework 4.8 Console app
2. Right click project > Convert to C#

### Error message shown
Output:
Converting ConverterTester.CSharpToVB...
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\MyNamespace.Static.1.Designer.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\MyNamespace.Static.2.Designer.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\Settings.Designer.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\Resources.Designer.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\AssemblyInfo.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\MyNamespace.Static.3.Designer.vb - conversion started

Phase 1 of 2:
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\MyNamespace.Static.3.Designer.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\Application.Designer.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\AssemblyInfo.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\Module1.vb - conversion started
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\Application.Designer.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\Module1.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\Settings.Designer.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\Resources.Designer.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\MyNamespace.Static.1.Designer.vb - conversion succeeded
* D:\Documents\Geeky\DotNet\ConverterTester.CSharpToVB\My Project\MyNamespace.Static.2.Designer.vb - conversion succeeded
Previous conversion cancelled

A VS status bar appears at the top of the screen showing 'Unfortunately, a process used by Visual Studio has encountered an unrecoverable error. We recommend saving your work, and then closing and restarting Visual Studio.'
Clicking 'Show Stack Trace' shows:
```csharp
StreamJsonRpc.RemoteInvocationException : Unexpected false
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Remote Exception) {
  "type": "System.InvalidOperationException",
  "message": "Unexpected false",
  "stack": "   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectInfoAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<CreateSolutionAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionService.<CreateSolution_NoLockAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionService.<GetSolutionAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.<>c__DisplayClass31_0.<<RenameSymbolAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.ServiceBase.<RunServiceAsync>d__14`1.MoveNext()",
  "code": -2146233079,
  "inner": null
} <--- 
```
### Details
* Product in use: VS extension
* Version in use: e.g. 8.1.4.0
* Using VS 2019 v16.7.0 Preview 3.0 0 believe it may have occurred with one of the recent VS preview updates

**Comment by GrahamTheCoder** [comment]
Thanks, I'll check this out soon. I'm pretty sure it worked on 16.6 preview 6, and I agree this sounds very much like a vs version incompatibility.

**Comment by GrahamTheCoder** [comment]
Appears to be caused by a caching bug in the VS workspace (doesn't occur in MSBuildWorkspace). I've worked around it by creating a new id (despite the id's docs specifically saying this isn't needed). I'll get this released and see if I can get an appropriate repro to raise an issue upstream.

**Comment by GrahamTheCoder** [comment]
Let me know if you still see any issues with the latest release. Thanks for letting me know about this!
