### ISSUE TITLE
Error on online converter 

### ISSUE THREAD

**Issue by sebastianolafhandjojo** [icsharpcode/CodeConverter#596]
this error happens in https://converter.telerik.com/
when trying to convert from VB to C#

## VB Code
Import System.Data.SqlClient

_' START From here is  OK_
string[] tags = new string[] { "ruby", "rails", "scruffy", "rubyonrails" };
string cmdText = "SELECT * FROM Tags WHERE Name IN ({0})";

string[] paramNames = tags.Select(
    (s, i) => "@tag" + i.ToString()
).ToArray();

string inClause = string.Join(", ", paramNames);
_' up until here is ok_ 

_' this is not working and throwing error_ 
using (SqlCommand cmd = new SqlCommand(string.Format(cmdText, inClause))) {
    for(int i = 0; i < paramNames.Length; i++) {
       cmd.Parameters.AddWithValue(paramNames[i], tags[i]);
    }
}

### Error message shown

Error converting code
Error message:
CONVERSION ERROR: Conversion for IncompleteMember not implemented, please report this issue in '(SqlCommand cmd ' at character 333
   at ICSharpCode.CodeConverter.VB.NodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitIncompleteMember(IncompleteMemberSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.IncompleteMemberSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitIncompleteMember(IncompleteMemberSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.IncompleteMemberSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.<VisitCompilationUnit>b__15_1(MemberDeclarationSyntax m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.VB.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.ConvertCompilationTree(CSharpCompilation compilation, CSharpSyntaxTree tree)
   at ICSharpCode.CodeConverter.VB.CSToVBConversion.SingleFirstPass(Compilation sourceCompilation, SyntaxTree tree)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.SingleFirstPass(SyntaxTree tree, String treeFilePath)
   at ICSharpCode.CodeConverter.Shared.ProjectConversion.FirstPass()

**Comment by GrahamTheCoder** [comment]
It looks like you're actually trying to convert C#->VB (though your input contains a mixture of both)
Thanks for the report, this bug is fixed in the latest version of the library - hosted at https://codeconverter.icsharpcode.net/

Input:
```csharp
using System.Data.SqlClient;
using System.Linq;

public class C 
{
    public void M()
    {
        // START From here is OK
        string[] tags = new string[] { "ruby", "rails", "scruffy", "rubyonrails" };
        string cmdText = "SELECT * FROM Tags WHERE Name IN ({0})";

        string[] paramNames = tags.Select(
        (s, i) => "@tag" + i.ToString()
        ).ToArray();

        string inClause = string.Join(", ", paramNames);
        // up until here is ok

        // this is not working and throwing error
        using (SqlCommand cmd = new SqlCommand(string.Format(cmdText, inClause))) {
            for(int i = 0; i < paramNames.Length; i++) {
                cmd.Parameters.AddWithValue(paramNames[i], tags[i]);
            }
        }
    }
}
```

Output:

```vbnet
Imports System.Data.SqlClient
Imports System.Linq

Public Class C
    Public Sub M()
        ' START From here is OK
        Dim tags As String() = New String() {"ruby", "rails", "scruffy", "rubyonrails"}
        Dim cmdText As String = "SELECT * FROM Tags WHERE Name IN ({0})"
        Dim paramNames As String() = tags.[Select](Function(s, i) "@tag" & i.ToString()).ToArray()
        Dim inClause As String = String.Join(", ", paramNames)

        ' up until here is ok

        ' this is not working and throwing error
        Using cmd As SqlCommand = New SqlCommand(String.Format(cmdText, inClause))

            For i As Integer = 0 To paramNames.Length - 1
                cmd.Parameters.AddWithValue(paramNames(i), tags(i))
            Next
        End Using
    End Sub
End Class

```

**Comment by sebastianolafhandjojo** [comment]
Hi Graham
Thanks for the fixes, 
I'm sorry I put the problem is converting from VB to C#, I just realized that
I have fixed it for documentation sake
