### ISSUE TITLE
VB -> C#: Exception converting linq expression with OrderBy and Distinct

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#635]
### Input code
```vbnet
' works fine
 Dim list = New List(Of String)
 Dim listSorted = From x In list Order By x
 Dim listDistinct = From x In listSorted Distinct
' exception
Dim listSortedDistinct = From x In list Order By x Distinct

### Erroneous output

#error Cannot convert LocalDeclarationStatementSyntax - see comment for details
            /* Cannot convert LocalDeclarationStatementSyntax, System.InvalidCastException Das Objekt des Typs "Microsoft.CodeAnalysis.CSharp.Syntax.EmptyStatementSyntax" kann nicht in Typ "Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax" umgewandelt werden.
               at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
               at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
               at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitLocalDeclarationStatement>d__31.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
             at ICSharpCode.CodeConverter.CSharp.HoistedNodeStateVisitor.<AddLocalVariablesAsync>d__6.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.<DefaultVisitInnerAsync>d__3.MoveNext()

### Details
* Product in use: VS extension 
* Version in use: 8.1.8.0
* Did you see it working in a previous version, which? No

**Comment by GrahamTheCoder** [comment]
Thanks for the report. The code in this area of the converter is a little convoluted, but debugging your test case should hopefully yield a straightforward enough fix. I'm a bit busy right now, but let me know if you're interested in having a go and I'll do my best to help out
