### ISSUE TITLE
VB -> C#: NameOf namespace'd method or property and character literal

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#639]
### Input code
```vbnet
    Public Sub New(ByVal cache As IOhmniPartAttributeRange, ByVal store As IOhmniPartAttributeRange)
        MyBase.New(New OhmniPartAttributeRangeNub, cache, store)
        Me.UsingNativeTracking = String.Equals(OhmniPartAttributeRangeBuilder.TableName, NameOf(IOhmniPartAttributeRange).TrimStart("I"c))
    End Sub
```

### Erroneous output
```C#
        public OhmniPartAttributeRangeEntity(IOhmniPartAttributeRange cache, IOhmniPartAttributeRange store) : base(new OhmniPartAttributeRangeNub(), cache, store)
        {
            ;
#error Cannot convert AssignmentStatementSyntax - see comment for details
            /* Cannot convert InvocationExpressionSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.EmptyStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax'.
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.<>c__DisplayClass78_0.<<ConvertInvocationAsync>g__ConvertInvocationSubExpression|0>d.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.<ConvertInvocationAsync>d__78.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.<VisitInvocationExpression>d__77.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.<ConvertHandledAsync>d__5`1.MoveNext()

            Input: NameOf(Global.isr.Dapper.Ohmni.IOhmniPartAttributeRange).TrimStart("I"c)
            Context:
                    Me.UsingNativeTracking = String.[Equals](Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeBuilder.TableName, NameOf(Global.isr.Dapper.Ohmni.IOhmniPartAttributeRange).TrimStart("I"c))

             */
        }
```

### Expected output
```C#
        public OhmniPartAttributeRangeEntity(IOhmniPartAttributeRange cache, IOhmniPartAttributeRange store) : base(new OhmniPartAttributeRangeNub(), cache, store)
        {
            this.UsingNativeTracking = String.Equals( isr.Dapper.Ohmni.OhmniPartAttributeRangeBuilder.TableName, nameof( isr.Dapper.Ohmni.IOhmniPartAttributeRange ).TrimStart( 'I' ) );
        }
```

### Details
* Product in use: codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) VS extension 
* Version in use: 8.1.8
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
Thanks for posting, I'm afraid I can't reproduce any of your issues on https://codeconverter.icsharpcode.net/
Can you provide more info on which version of which converter you're using?

**Comment by GrahamTheCoder** [comment]
Consolidating
