### ISSUE TITLE
C# -> VB: Support Block syntax

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#64]
```
Error processing ICSharpCode.CodeConverter\Util\SyntaxTokenExtensions.cs
In 'C:\Users\Graham\Documents\GitHub\CodeConverter\ICSharpCode.CodeConverter\Util\SyntaxTokenExtensions.cs':
System.NotImplementedException: Cannot convert BlockSyntax from '{
					var ...' at character 35965
 in '{
				// look for'
   at ICSharpCode.CodeConverter.VB.CSharpConverter.MethodBodyVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.MethodBodyVisitor.<ConvertBlock>b__39_1(StatementSyntax s)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.MethodBodyVisitor.ConvertBlock(StatementSyntax node)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.MethodBodyVisitor.VisitDoStatement(DoStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.DoStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitDoStatement(DoStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.DoStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.<>c__DisplayClass34_0.<VisitMethodDeclaration>b__0(StatementSyntax s)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
   at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.<VisitClassDeclaration>b__24_0(MemberDeclarationSyntax m)
   ...
```

**Comment by RussellSmith2** [comment]
Here is VisitBlock.  I didn't have time to do a pull request or write the test.

```
public override SyntaxList<StatementSyntax> VisitBlock(CSS.BlockSyntax node)
{
	SyntaxList<StatementSyntax> Statements = ConvertBlock(node);
	IfStatementSyntax IfStatement = SyntaxFactory.IfStatement(SyntaxFactory.Token(
		SyntaxKind.IfKeyword), 
		SyntaxFactory.TrueLiteralExpression(SyntaxFactory.Token(SyntaxKind.TrueKeyword)), 
		SyntaxFactory.Token(SyntaxKind.ThenKeyword)
	);

	MultiLineIfBlockSyntax IfBlock = SyntaxFactory.MultiLineIfBlock(IfStatement, Statements, SyntaxFactory.List<ElseIfBlockSyntax>(), null);

	return SyntaxFactory.SingletonList<StatementSyntax>(IfBlock);
}
```

**Comment by GrahamTheCoder** [comment]
Seems reasonable, I'll try to get it integrated soon
