### ISSUE TITLE
NullReferenceException converting VB to C#

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#653]
### Steps to reproduce
Most of my projects convert fine. With some of them I got an exception after converting (vb files are converted, but not vbproj)

### Error message shown

Code converter 8.1.8 - Visual Studio 16.0.30523.141
```csharp
An error has occured during conversion - press Ctrl+C to copy the details: System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<WriteConvertedFilesAndShowSummaryAsync>d__17.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<WriteConvertedFilesAndShowSummaryAsync>d__17.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass13_0`1.<<ConvertProjectsAsync>b__0>d.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertProjectsAsync>d__13`1.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<SolutionOrProjectMenuItemCallbackAsync>d__23.MoveNext()
```

### Details
* Product in use: VS extension
* Version in use: 8.1.8.0
* Did you see it working in a previous version, which? no

**Comment by GrahamTheCoder** [comment]
I've pushed a fix based on the most likely cause of this, would be great to retest from source/ci or next release

**Comment by KunzeAndreas** [comment]
Thank you for fixing the bug. Now it works.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting and testing!
