### ISSUE TITLE
Extension MissingMethodException on any conversion

### ISSUE THREAD

**Issue by tugibaev** [icsharpcode/CodeConverter#654]
1. Installed extension from MS Store to VS2019 pro;
2. Open simplest VB project;
3. Select single file from solution explorer;
4. "Convert to C#"
5. Error:
```
---------------------------
Code converter 8.1.8 - Visual Studio 16.0.30523.141
---------------------------
An error has occured during conversion - press Ctrl+C to copy the details: System.MissingMethodException: Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.DocumentId> Microsoft.CodeAnalysis.Solution.GetDocumentIdsWithFilePath(System.String)'.

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentUnhandledAsync>d__23`1.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.ConvertDocumentUnhandledAsync[TLanguageConversion](String documentPath, Span selected, CancellationToken cancellationToken)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass14_0`1.<<ConvertDocumentAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentAsync>d__14`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<ConvertDocumentAsync>d__24.MoveNext()
---------------------------
OK   
---------------------------
```
All latest updates are installed. Core 3.1.402.

**Comment by GrahamTheCoder** [comment]
Thanks, this sounds like it could be an API change in the latest version of Visual Studio. I'll grab the latest version and try it now

**Comment by GrahamTheCoder** [comment]
I've checked this on the latest preview, 16.8.0 preview 3.2 and it works fine for me.

The method mentioned is still in master: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L1730

It has had the same method signature for 6 years since it was first added:
https://github.com/dotnet/roslyn/blame/286914ce77e93a5cbe574b373c9de18decdf2fde/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L1843

This means it's either loading a very old version of that dll, or a corrupt one.
* The first thing I'd suggest is running a repair install on your Visual Studio install, then restart VS and try again.
* Then try disabling all other extensions then retart VS and try again.

Finally, you could attach a second Visual Studio instance and post here the path/version of the dll containing that method (Microsoft.CodeAnalysis.Workspaces):
![image](https://user-images.githubusercontent.com/2490482/95763116-89be8100-0ca6-11eb-9174-f71fc7a6d19e.png)
![image](https://user-images.githubusercontent.com/2490482/95763247-b2467b00-0ca6-11eb-943e-8988ea08983c.png)

Thanks!

**Comment by artemibe** [comment]
I was disable all other extensions installed and it's works. I think this code must be in try/catch block with some message to disable extensions.
