### ISSUE TITLE
VB -> C#: Cannot convert InvocationExpressionSyntax, System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#673]
### Input code
```vbnet
        Public Shared Sub Identify(ByVal talker As ITraceMessageTalker)
            talker?.IdentifyTalker(IdentityTraceMessage())
        End Sub
```

### Erroneous output
```C#
        public static void Identify(ITraceMessageTalker talker)
        {
            ;
#error Cannot convert ExpressionStatementSyntax - see comment for details
            /* Cannot convert InvocationExpressionSyntax, System.ArgumentNullException: Value cannot be null.
            Parameter name: node
               at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoForNode(SyntaxNode node, CancellationToken cancellationToken)
               at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.MayThrow(ExpressionSyntax expression)
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.FirstArgDefinitelyEvaluated(InvocationExpressionSyntax parentInvocation)
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.DefinitelyExecutedAfterPreviousStatement(InvocationExpressionSyntax invocation)
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.RequiresLocalFunction(InvocationExpressionSyntax invocation, IMethodSymbol invocationSymbol)
               at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.<VisitInvocationExpression>d__77.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.<ConvertHandledAsync>d__5`1.MoveNext()

            Input: Global.isr.Algorithms.Signals.My.MyLibrary.IdentityTraceMessage()
            Context:
                        talker?.IdentifyTalker(Global.isr.Algorithms.Signals.My.MyLibrary.IdentityTraceMessage())

             */
        }
```

### Expected output
```C#
        public static void Identify(ITraceMessageTalker talker)
        {
            talker?.IdentifyTalker( global::isr.Algorithms.Signals.My.MyLibrary.IdentityTraceMessage() );
        }

or
        public static void Identify(ITraceMessageTalker talker)
        {
            talker?.IdentifyTalker( IdentityTraceMessage() );
        }
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension
* Version in use: 8.1.8.0 artifact of 10/12
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. 

This seems to be an issue with the Global. vs. global:: conversion.  Was the artifact addressing the Global syntax?

**Comment by GrahamTheCoder** [comment]
Thanks, I can reproduce the issue when converting [this minimal compilable unit of VB](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUPQAoCuEwAlgMaEDCwAhviIBBPoPz1CU6VJZsuJABb9slGCVaFkMSgDtc7AGakAFACFSANX7BCuGwGtK2QsKLIAKtn6dKAWUohfgBzSg9HZwBKSRlYqXtgJ2wAfgA6bT0DY3DE5xMM/XZcUi8ff0D8EMoTSOi6OKkAUV11YlZ6GNlsdjB+KiUVNUIAMWZdTgNMXS0dQuLS3wCg0JrXIgB5CAArSgnO2I9FbEwAd0IAOUoz88xcNHRgaky1RoAPX3RJ3Rr95vVR8Zfeh/XgCIQdOhyDjcZD6ZyGMpaBblZZhCLYfYAibsKYzTJGErokxgNaETY7CaRUnk3a4YEtLRw7AI3z0IA)  without any other context:
```vbnet
Imports System

Public Class AClass
        Public Shared Sub Identify(ByVal talker As ITraceMessageTalker)
            talker?.IdentifyTalker(IdentityTraceMessage())
        End Sub

    Private Shared Function IdentityTraceMessage() As Object
        Throw New NotImplementedException()
    End Function
End Class

Public Interface ITraceMessageTalker
    Function IdentifyTalker(v As Object) As Object
End Interface
```
The simplest fix would be just to return true if there's no symbol here:
https://github.com/icsharpcode/CodeConverter/blob/70207de6b838de6cc05c4ecf414addd279b3268e/CodeConverter/CSharp/ExpressionNodeVisitor.cs#L981-L987
