### ISSUE TITLE
Cannot convert SelectBlockSyntax, System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Chiel92** [icsharpcode/CodeConverter#707]
### Steps to reproduce
1. Convert VB to C# on the code shown in the error message below

### Error message shown
```
            /* Cannot convert SelectBlockSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
               at ICSharpCode.CodeConverter.CSharp.VisualBasicEqualityComparison.VbCoerceToNonNullString(ExpressionSyntax vbNode, ExpressionSyntax csNode, TypeInfo typeInfo, Boolean knownNotNull)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicEqualityComparison.VbCoerceToNonNullString(ExpressionSyntax vbLeft, ExpressionSyntax csLeft, TypeInfo lhsTypeInfo, Boolean leftKnownNotNull, ExpressionSyntax vbRight, ExpressionSyntax csRight, TypeInfo rhsTypeInfo, Boolean rightKnownNotNull)
               at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitSelectBlock>d__65.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.HoistedNodeStateVisitor.<AddLocalVariablesAsync>d__6.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.<DefaultVisitInnerAsync>d__3.MoveNext()

            Input:
                        Select Case Global.Microsoft.VisualBasic.Strings.LCase(sort.Value) ' LCase can also hande Nothing
                            Case "asc", "ascending", "desc", "descending", "", Nothing
                            Case Else
                                Errors.ValidationError(Me, "{0} field '{1}' has invalid sort-order '{2}'.", FieldTypeDisp, sort.[Key], sort.Value)
                        End Select

             */
```

### Details
* Product in use: VS extension
* Version in use: 8.2.2.0

**Comment by GrahamTheCoder** [comment]
Thanks for the report, I'll try to take a look this weekend

**Comment by Chiel92** [comment]
Thanks!
