### ISSUE TITLE
VB -> C#: Error when converting LINQ expression

### ISSUE THREAD

**Issue by dfbag7** [icsharpcode/CodeConverter#717]
### Input code
```vbnet
    Sub Main()
        Dim arr(5) as Integer
        arr(0) = 0
        arr(1) = 1
        arr(2) = 2
        arr(3) = 3
        arr(4) = 4
        arr(5) = 5

        Dim r = From e In arr
                Select p = $"value: {e}"

        For each m In r
            Console.WriteLine(m)
        Next
    End Sub
```

### Erroneous output
```C#
    static class Module1
    {
        public static void Main()
        {
            var arr = new int[6];
            arr[0] = 0;
            arr[1] = 1;
            arr[2] = 2;
            arr[3] = 3;
            arr[4] = 4;
            arr[5] = 5;
            ;
#error Cannot convert LocalDeclarationStatementSyntax - see comment for details
            /* Cannot convert LocalDeclarationStatementSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.EmptyStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax'.
               at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
               at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
               at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitLocalDeclarationStatement>d__31.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.HoistedNodeStateVisitor.<AddLocalVariablesAsync>d__6.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.<DefaultVisitInnerAsync>d__3.MoveNext()

            Input:

                    Dim r = From e In arr
                            Select p = $"value: {e}"

             */
            foreach (var m in r)
                Console.WriteLine(m);
        }
    }
```

### Expected output
I believe the LINQ statement should be converted into something like this:
```C#
   var r = from e in arr
      let p = $"value: {e}"
      select p;
```
The reason is that, in VB.NET, the `Select` LINQ statement with assignments seems working like `let` in C# with following `select` of the variable defined in the `let` statement.

### Details
* Product in use: VS extension
* Version in use: 8.2.2.0
* Did you see it working in a previous version, which? _Did not test in previous versions_

**Comment by GrahamTheCoder** [comment]
Thanks, I hadn't seen this syntax before. The linq conversion code is more complicated than the rest of the converter, but I think this specific case could probably be added easily enough.

If anyone wants to have a go at this, as always, just run the above example under a debugger and see where it initially throws. Probably somewhere around here:
https://github.com/icsharpcode/CodeConverter/blob/2fe32234742e1417988f7d1451b120f669801c3d/CodeConverter/CSharp/QueryConverter.cs#L266
