### ISSUE TITLE
Conversion failed at one of solution projects

### ISSUE THREAD

**Issue by AhmedSuror** [icsharpcode/CodeConverter#725]
```csharp
Phase 1 of 2:
* RayLab\Forms\FrmMain.vb - conversion started
* RayLab\Forms\FrmMain.vb - conversion has errors: 
    Conversion warning: Name qualification failed for this file. System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax'.
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitWithEventsPropertyEventContainer(WithEventsPropertyEventContainerSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.WithEventsPropertyEventContainerSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitHandlesClauseItem(HandlesClauseItemSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseItemSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitHandlesClause(HandlesClauseSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodStatement(MethodStatementSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(MethodBlockSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
       at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
       at ICSharpCode.CodeConverter.Shared.DocumentExtensions.<ExpandAsync>d__4.MoveNext()

Phase 2 of 2:
* RayLab\Forms\FrmMain.vb - simplification started
* RayLab\Forms\FrmMain.vb - simplification has errors: 
    Conversion warning: Name qualification failed for this file. System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax'.
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitWithEventsPropertyEventContainer(WithEventsPropertyEventContainerSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.WithEventsPropertyEventContainerSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitHandlesClauseItem(HandlesClauseItemSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseItemSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitHandlesClause(HandlesClauseSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodStatement(MethodStatementSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(MethodBlockSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
       at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
       at ICSharpCode.CodeConverter.Shared.DocumentExtensions.<ExpandAsync>d__4.MoveNext()
```

**Comment by GrahamTheCoder** [comment]
Thanks for the report. It looks like a bug in the VB Microsoft Code Analysis library with "Handles" clauses that have `x.y` in them (rather than just `y`)

It would help if you could provide the file causing the issue (or at least the parts of it with Handles clauses) then I can try to work around the issue, and possibly report/fix it in the Microsoft codebase upstream

**Comment by samuelGrahame** [comment]
just got the same exception above.

**Comment by AhmedSuror** [comment]
> issue

Thanks for your reply, I hope that you can help.
This is the file (Just Subs with handle clauses):

Option Strict On
Imports System
Imports System.IO
Imports System.Data
Imports System.Data.OleDb
Imports Config.Reg
Imports UniData
Imports Microsoft.Reporting.WinForms
Imports System.Globalization
Imports System.Threading
Imports System.Threading.Tasks

Public Class FrmMain
    Public CurrentUser As User

    Private Sub FrmMain_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
		'Some Code
    End Sub

    Private Sub FrmMain_Shown(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Shown
		'Some Code	
    End Sub

    Private Async Sub FSWDBFile_Changed(ByVal sender As System.Object, ByVal e As System.IO.FileSystemEventArgs) Handles FSWDBFile.Changed
		'Some Code
    End Sub

    Private Sub RibbonControlAdv1_OfficeMenu_ItemClicked(sender As Object, e As ToolStripItemClickedEventArgs) Handles RibbonControlAdv1.OfficeMenu.ItemClicked
		'Some Code
    End Sub

    Private Sub ToolStripButton7_Click(sender As Object, e As EventArgs) Handles ToolStripButton7.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton8_Click(sender As Object, e As EventArgs) Handles ToolStripButton8.Click
       'Some Code
    End Sub

    Private Sub ToolStripButton9_Click(sender As Object, e As EventArgs) Handles ToolStripButton9.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton4_Click(sender As Object, e As EventArgs) Handles BtnAddRay.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton5_Click(sender As Object, e As EventArgs) Handles ToolStripButton5.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton2_Click(sender As Object, e As EventArgs) Handles BtnAddDocs.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton3_Click(sender As Object, e As EventArgs) Handles ToolStripButton3.Click
        'Some Code
    End Sub

    Private Sub عرضجميعالحالاتالمحولةToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles عرضجميعالحالاتالمحولةToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub عرضتفاصيلالحالاتالمحولةToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles عرضتفاصيلالحالاتالمحولةToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton6_Click(sender As Object, e As EventArgs) Handles ToolStripButton6.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton10_Click(sender As Object, e As EventArgs) Handles BtnRestBak.Click
		'Some Code	
    End Sub
    
    Private Sub ToolStripButton14_Click(sender As Object, e As EventArgs) Handles ToolStripButton14.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton13_Click(sender As Object, e As EventArgs) Handles ToolStripButton13.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton12_Click(sender As Object, e As EventArgs) Handles ToolStripButton12.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton16_Click(sender As Object, e As EventArgs) Handles ToolStripButton16.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton19_Click(sender As Object, e As EventArgs) Handles ToolStripButton19.Click
       'Some Code
    End Sub

    Private Sub ToolStripButton18_Click(sender As Object, e As EventArgs) Handles ToolStripButton18.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton17_Click(sender As Object, e As EventArgs) Handles ToolStripButton17.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton20_Click(sender As Object, e As EventArgs) Handles ToolStripButton20.Click
		'Some Code
    End Sub

    Private Sub SfButton7_Click(sender As Object, e As EventArgs) Handles btnUsers.Click
        'Some Code
    End Sub

    Private Sub SfButton6_Click(sender As Object, e As EventArgs) Handles SfButton6.Click
        'Some Code
    End Sub

    Private Sub SfButton4_Click(sender As Object, e As EventArgs) Handles BtnDbPath.Click
       'Some Code
    End Sub

    Private Sub SfButton5_Click(sender As Object, e As EventArgs) Handles BtnBakPath.Click
        'Some Code
    End Sub

    Private Sub BackStageButton3_Click(sender As Object, e As EventArgs) Handles BackStageButton3.Click
        'Some Code
    End Sub

    Private Sub SplitbuttonsClick(sender As Object, e As EventArgs) Handles ToolStripButton1.Click, ToolStripButton11.Click
      'Some Code
    End Sub

    Private Sub استعلامبالنقاطToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles استعلامبالنقاطToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub استعلامعنالأطباءبدوننقاطToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles استعلامعنالأطباءبدوننقاطToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub استعلامعنأفضل10أطباءبالنقاطToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles استعلامعنأفضل10أطباءبالنقاطToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton15_ButtonClick(sender As Object, e As EventArgs) Handles ToolStripButton15.Click
        'Some Code
    End Sub

    Private Sub ToolStripButton11_ButtonClick(sender As Object, e As EventArgs) Handles ToolStripButton11.ButtonClick

    End Sub

    Private Sub محددعامToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles محددعامToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub محددمجمعToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles محددمجمعToolStripMenuItem.Click
        'Some Code
    End Sub

    Private Sub lblNotification_Click(sender As Object, e As EventArgs) Handles lblNotification.Click
        't'Some Code
    End Sub

    Private Sub SfButton2_Click(sender As Object, e As EventArgs) Handles SfButton2.Click
        'Some Code
    End Sub

End Class

**Comment by GrahamTheCoder** [comment]
I believe I've accurately reproduced the issue. It's this Handles clause causing the issue:
```vbnet
    Private Sub RibbonControlAdv1_OfficeMenu_ItemClicked(sender As Object, e As ToolStripItemClickedEventArgs) Handles RibbonControlAdv1.OfficeMenu.ItemClicked
        'Some Code
    End Sub
```
However, I can't find a way to make this compile, even if I create a field called RibbonControlAdv1 that has a field called OfficeMenu, the compiler says:
`Error	BC31412	'Handles' in classes must specify a 'WithEvents' variable, 'MyBase', 'MyClass' or 'Me' qualified with a single identifier.`
Does this compile for you? Presumably the ribbon control is the one from SyncFusion? Do you know of anything special going on with this?

As a workaround for conversion, try commenting this and any other Handles clause which has two or more dots in it

Thanks!

**Comment by AhmedSuror** [comment]
Exactly, That was the problem (2 dotted handles clause), Thanks very much..
This is the first time I use this tool, the solution has been compiled and ran perfectly, I wish that no problem arise out in the long term.
Some other things I didn't get, like:
- Program.cs, where is it (it seems that it is the old "ApplicationEvents.cs")?
- Forms initializers voids contain some controls properties which - in normal c# - are in InitilizeComponents in the Forms Designer.
- The namespace "Microsoft.VisualBasic.CompilerServices", I know it is used for some old converted VB files, is there a way to remove it and replace all its classes using PURE C# code?
Thanks again.

**Comment by AhmedSuror** [comment]
> 
> 
> That's good to know. Since I can't get a compiling example though, I can't fix the problem for future users unfortunately.
> 
>     * Program.cs: Sorry I don't know what you mean. File.vb is converted to File.cs in almost every case - a few extra files are added that VB would generate during compilation.
> 
>     * winforms initialization: Names have to be set separately for maximum compatibility
> 
>     * Getting rid of VB library: The functions used are usually a wrapper around something in the framework but with some special VB works added. Automatically replacing would either need lots of code inlined, or risk changing behaviour. At some point I'd like to investigate more of these, see #174 For the moment, it will need manual changes from you (or Find/replace)
> 
> 
> Good luck!

Program.cs is the main entry point of a C# application.
Anyway, thanks very much for your cooperation.
