### ISSUE TITLE
Artifacts & crash

### ISSUE THREAD

**Issue by kopycol** [icsharpcode/CodeConverter#770]
There is no this bug when just open Visual Studio.
There are some artifacts that can be reason.
After converting from C# to VB (even with deleted Vb file) Ctrl+S don't simple save *.cs file but prompted for name (as Save As).
After the next converting it gives this exception:

---------------------------
Code converter 8.4.0 - Visual Studio 16.11.31702.278
---------------------------
An error has occurred during conversion - press Ctrl+C to copy the details: System.NullReferenceException: Object reference not set to an instance of an object.
```
at ICSharpCode.CodeConverter.VsExtension.VisualStudioInteraction.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at ICSharpCode.CodeConverter.VsExtension.CodeConversion.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at ICSharpCode.CodeConverter.VsExtension.CodeConversion.d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass14_0`1.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask`1.<g__JoinSlowAsync|3_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ICSharpCode.CodeConverter.VsExtension.CodeConversion.d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
---------------------------
OK   
---------------------------

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report, I'll try to investigate at the weekend. Can you confirm which menu item you used for the conversion (e.g. file/project/solution in solution explorer, the file's document tab, the edit menu)?

The error sounds like the file selected second is no longer in the active solution.

**Comment by kopycol** [comment]
I used file text right mouse menu,

**Comment by GrahamTheCoder** [comment]
I've put in a possible fix for this, let me know if you find it works for you now
