### ISSUE TITLE
OutOfMemoryException (lots of large winforms designer files)

### ISSUE THREAD

**Issue by sanketgroup** [icsharpcode/CodeConverter#850]
### Steps to reproduce

1. I downloaded and installed latest version 8.4.6.0 from https://marketplace.visualstudio.com/
2. I opened my VB.net project in VS2019 and right-clicked "Convert to C#". The project has around 1200 VB forms including designer forms. Phase 1 was completed after 7 hours with having one error in one form.
3. Phase 2 started, after around 40 forms I got the following error.

### Error message shown
```
https://github.com/dotnet/roslyn threw an exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Resize()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.CreateEntry(TKey key, TValue value)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.GreenNode..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CastExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CastExpressionSyntax.<>c.<.cctor>b__24_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ParenthesizedExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ParenthesizedExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.InvocationExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.InvocationExpressionSyntax.<>c.<.cctor>b__18_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionStatementSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExpressionStatementSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithLotsOfChildren.<>c.<.cctor>b__0_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BlockSyntax.<>c.<.cctor>b__24_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MethodDeclarationSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MethodDeclarationSyntax.<>c.<.cctor>b__45_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithLotsOfChildren.<>c.<.cctor>b__0_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ClassDeclarationSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ClassDeclarationSyntax.<>c.<.cctor>b__45_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.NamespaceDeclarationSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.NamespaceDeclarationSyntax.<>c.<.cctor>b__42_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax.<>c.<.cctor>b__27_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.DeserializeFrom(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.DeserializeNodeFrom(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.RecoverRoot(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.Recover(CancellationToken cancellationToken)
   at Roslyn.Utilities.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.RecoverableSyntaxTree.GetRoot(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetRootCore(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.PositionalSyntaxReference.GetSyntax(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.AddDeclaredNontypeMembers(DeclaredMembersAndInitializersBuilder builder, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.<BuildMembersAndInitializers>g__buildDeclaredMembersAndInitializers|152_1(BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.<BuildMembersAndInitializers>g__getDeclaredMembersAndInitializers|152_0()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.BuildMembersAndInitializers(BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembersAndInitializers()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.MakeAllMembers(BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembersByNameSlow()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembersByName()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetMembers(String name)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.GetConstructors(Boolean includeInstance, Boolean includeStatic)
   at Microsoft.CodeAnalysis.CSharp.Binder.GetAccessibleConstructorsForOverloadResolution(NamedTypeSymbol type, Boolean allowProtectedConstructorsOfBaseType, ImmutableArray`1& allInstanceConstructors, CompoundUseSiteInfo`1& useSiteInfo)
   at Microsoft.CodeAnalysis.CSharp.Binder.TryPerformConstructorOverloadResolution(NamedTypeSymbol typeContainingConstructors, AnalyzedArguments analyzedArguments, String errorName, Location errorLocation, Boolean suppressResultDiagnostics, BindingDiagnosticBag diagnostics, MemberResolutionResult`1& memberResolutionResult, ImmutableArray`1& candidateConstructors, Boolean allowProtectedConstructorsOfBaseType)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindClassCreationExpression(SyntaxNode node, String typeName, SyntaxNode typeNode, NamedTypeSymbol type, AnalyzedArguments analyzedArguments, BindingDiagnosticBag diagnostics, InitializerExpressionSyntax initializerSyntaxOpt, TypeSymbol initializerTypeOpt, Boolean wasTargetTyped)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindClassCreationExpression(ObjectCreationExpressionSyntax node, NamedTypeSymbol type, String typeName, BindingDiagnosticBag diagnostics, TypeSymbol initializerType)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindObjectCreationExpression(ObjectCreationExpressionSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInferredVariableInitializer(BindingDiagnosticBag diagnostics, ExpressionSyntax initializer, BindValueKind valueKind, RefKind refKind, CSharpSyntaxNode errorSyntax)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, BindingDiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, VariableState nullableInitialState, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass23_0.<CompileNamedTypeAsync>b__0()

https://github.com/dotnet/roslyn threw an exception: System.InvalidOperationException: Exception of type 'System.InvalidOperationException' was thrown.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.VerifyIntegrity()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.GreenNode..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.MemberAccessExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ParenthesizedExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ParenthesizedExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.<>c.<.cctor>b__21_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.ReadObject()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.ReadValue()
```

**Comment by GrahamTheCoder** [comment]
Thanks for the report. The roslyn formatter's memory usage scales very badly with file size, so for designer forms which end up as very large files (especially after conversion), it might be worth trying either in VS2022, or in the command line.
Someone else had success in a similar situation here: https://github.com/icsharpcode/CodeConverter/issues/605#issuecomment-673959130

I'll leave this issue open though since it'd be good to have another go at working around this problem somehow (even if just giving better information within the tool).

**Comment by sanketgroup** [comment]
How do I run it from CLI?
I went to Tools > Command Line > Developer Command Prompt

I typed "codeconv [Source Parth]"
It says  ' codeconv' not recognized.

**Comment by sanketgroup** [comment]
When I run following command via CLI (command prompt), it just shows me following message and does nothing.

Command: (in Comman prompt)
C:\Users\test\.dotnet\tools\codeconv -t cs -b E:\Projects\SourceProj\test.sln

I get a reply and then nothing.

"Using .NET Framework MSBuild from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"

Am I doing something wrong to covert via CLI?

**Comment by GrahamTheCoder** [comment]
Did the command `dotnet tool install ICSharpCode.CodeConverter.codeconv --global` succeed?

**Comment by GrahamTheCoder** [comment]
I've reproduced the issue you're having - it seems to be a problem with more recent releases. I'm just trying to find where the issue was introduced. e.g. It wasn't in 8.1.7

**Comment by sanketgroup** [comment]
okay, i tried with --force --core-only
**Execute Command:**
C:\Users\developers\.dotnet\tools\codeconv -t cs -b E:\Projects\SourceProj\test.sln

**Result:**
Continuing with possibility of data loss due to force option.

WARNING: There are files in E:\Projects\SourceProj which may be overwritten, and aren't comitted to git

Running dotnet restore on E:\Projects\SourceProj\test.sln
  Determining projects to restore...
  Nothing to do. None of the projects specified contain packages to restore.

System.TypeLoadException   at Microsoft.Build.Construction.SolutionFile.set_FullPath(String value)
   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadSolutionInfoAsync(String solutionFilePath, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenSolutionAsync(String solutionFilePath, IProgress`1 progress, CancellationToken cancellationToken)
   at ICSharpCode.CodeConverter.CommandLine.MSBuildWorkspaceConverter.GetSolutionAsync(String projectOrSolutionFile, IProgress`1 progress) in /_/CommandLine/CodeConv.Shared/MSBuildWorkspaceConverter.cs:line 76
   at ICSharpCode.CodeConverter.CommandLine.MSBuildWorkspaceConverter.<>c__DisplayClass7_0.<<ConvertProjectsWhereAsync>b__1>d.MoveNext() in /_/CommandLine/CodeConv.Shared/MSBuildWorkspaceConverter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---

**Comment by GrahamTheCoder** [comment]
Does that same error also happen on 8.4.1.154? I think something pretty serious went wrong in the releases after that

**Comment by sanketgroup** [comment]
No, i haven't tried 8.4.1.154

Conversation in Visual studio via context menu also seems slower than previously.

**Comment by GrahamTheCoder** [comment]
Sorry you're having such a terrible time trying to get this working.

I haven't seen that error before, was there any more to it? Usually it should have a message saying which type couldn't be initialized, but that might have got cut off somehow. There have been some versions of Visual Studio shipped with some mismatched versions that could cause this sort of problem (one of them was mentioned here: https://github.com/dotnet/msbuild/issues/5883)

Just to check, when you say "slower than previously", did anything change since it was fast (e.g. different version), or just randomly is slower?

**Comment by sanketgroup** [comment]
Thanks for all your support to the community.

Slower than week older version.
I have never tried VS2022. 

I am working on 2019.
Last week I was trying to convert project having around 500,000 line, phase 1 completed in around 7-9 hrs.
Phase2 worked for few hrs than it thew out of memory error.

But 3 days before, I downloaded latest CodeConvert version and tried to convert same project.
It has been around 63 hrs since it started and even phase 1 is not completed, and it is still working. Don't know when it will finish.

Then yesterday I tried on different PC (i7 16gb memory), same issue.
Almost after 18 hrs, phase 1 not completed.

Output windows shows list of forms being converted. What I observed is extremly longer time than it was doing week before when seeing output window.

**Comment by GrahamTheCoder** [comment]
When trying within Visual Studio, you could try decreasing this option:
![image](https://user-images.githubusercontent.com/2490482/158029457-a7b7983d-423e-4bbf-a34b-493ed190d84e.png)
It will probably make a mess of a bunch of the files, but it may be good enough that you can autoformat them afterwards.

What's the target framework of the project you're trying to convert by the way?

**Comment by sanketgroup** [comment]
It's VB. Net to c# 
.Net 4.5.2

**Comment by GrahamTheCoder** [comment]
I'm hoping to release a fix reasonably soon for the general issue where it couldn't find the dot net framework exe. In the meantime you could try this as a workaround:
1. Download the package containing the tool and unzip it somewhere https://www.nuget.org/api/v2/package/ICSharpCode.CodeConverter.CodeConv/8.4.6.318
(If you rename from .nupkg to .zip extension you can easily extract the files)
2. Run the net framework exe directly (e.g.):
```cmd
cd C:\Users\developers.dotnet\Downloads\icsharpcode.codeconverter.codeconv.8.4.6.318\tools\any\NetFramework
ICSharpCode.CodeConverter.CodeConv.NetFramework.exe E:\Projects\SourceProj\test.sln -t cs --force -b
```

There's still another issue I'm looking into regarding an error loading "ImmutableList", but it may not actually cause an issue with the conversion.

**Comment by GrahamTheCoder** [comment]
The commandline with one of the fixes is now released, so you can run
`dotnet tool update --global ICSharpCode.CodeConverter.CodeConv` instead of doing anything in my previous post
When you try the new one, don't use the --core-only flag (since your project is a framework project). _Hopefully_ it should at least do more than exit after one line now...

**Comment by GrahamTheCoder** [comment]
Consolidated into other issues
