### ISSUE TITLE
VB -> C#: Comma in FromClause of Query Syntax is not correctly identified as alternate syntax for another FromClause

### ISSUE THREAD

**Issue by jrmoreno1** [icsharpcode/CodeConverter#853]
### VB.Net input code
```vbnet
Public Class VisualBasicClass
Sub Main
	Dim list1 As New List(Of Integer)() From {1,2,3}
	Dim list2 As New List(Of Integer) From {2, 4,5}
	
	Dim qs = From n In list1, x In list2
			 Where x = n 
			 Select New With {x, n}

	For Each a In qs
		Console.WriteLine($"n={a.n}")
		Console.WriteLine($"x={a.x}")
	Next 
End Sub
End Class
```

### Erroneous output
```C#
using System.Collections.Generic;

public partial class VisualBasicClass
{
    public void Main()
    {
        var list1 = new List<int>() { 1, 2, 3 };
        var list2 = new List<int>() { 2, 4, 5 };
        var qs = default
#error Cannot convert QueryExpressionSyntax - see comment for details
/* Cannot convert QueryExpressionSyntax, System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertFromClauseSyntaxAsync(FromClauseSyntax vbFromClause) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 0
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertClausesAsync(SyntaxList`1 clauses) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 43
   at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitQueryExpression(QueryExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 655
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 48

Input:
From n In list1, x In list2
			 Where x = n 
			 Select New With {x, n}

 */
;
        foreach (var a in qs)
        {
            Console.WriteLine($"n={a.n}");
            Console.WriteLine($"x={a.x}");
        }
    }
}
```
### Expected output
```C#
using System.Collections.Generic;

public partial class VisualBasicClass
{
    public void Main()
    {
        var list1 = new List<int>() { 1, 2, 3 };
        var list2 = new List<int>() { 2, 4, 5 };
        var qs = from n in list1
			 from x in list2
			 where x == n
			 select new { x, n };


	foreach (var a in qs)
	{
		Console.WriteLine($"n={a.n}");
		Console.WriteLine($"x={a.x}");
	}
}
```

### Details
* codeconverter.icsharpcode.net / VS extension 
* never saw it working
* Any other relevant information to the issue, or your interest in contributing a fix.

Basically in a VB.net query syntax query, the "From" can optionally be replaced with a comma. Aka inside a FromClause a CommaToken followed by a CollectionRangeVariable can be replaced with another FromeClause with the CollectionRangeVariable that follows the comma.

**Comment by GrahamTheCoder** [comment]
Thanks for the repro. Obvious the temporary workaround is to replace the "," with "from" (assuming that means the same). I hadn't seen this syntax before but it should be pretty easy to support if it means the same

**Comment by jrmoreno1** [comment]
It does, I've actually looked into fixing it myself, and was able to do so, but I'm not too crazy about how it looks.

**Comment by GrahamTheCoder** [comment]
Thanks, that looks like a great start. The query syntax code is in general a bit hacky but I'll see if I can see if there's a way to avoid ".First()"

**Comment by jrmoreno1** [comment]
Made some minor changes in that PR, but it looks like it's partially buried in inadvertent white space changes.

**Comment by GrahamTheCoder** [comment]
Last week I did have a go at fixing this starting from your test. I've opened it as a draft PR since it's messy enough that I'm not quite comfortable merging without more thought at least.
