### ISSUE TITLE
VB -> C#: NotImplementedException during conversion (ParenthesizedExpression)

### ISSUE THREAD

**Issue by CardenInsurance** [icsharpcode/CodeConverter#936]
The actual LINQ query that caused this error was really big, but I whittled it down using the online converter (great tool) to just this:

### VB.Net input code
```vbnet
Public Class VisualBasicClass
    Public Sub abc()
        Using db As New PRIMEEntities
            results.AddRange(From pCurrent In db.Policies
                            Join pPrevious In db.Policies On pCurrent.Reinsurance_Year - 1 Equals pPrevious.Reinsurance_Year
                            Select Policy_ID)
        End Using
    End Sub
End Class
```

### Erroneous output
```C#
public partial class VisualBasicClass
{
    public void abc()
    {
        using (var db = new PRIMEEntities())
        {
            results.AddRange(default
#error Cannot convert QueryExpressionSyntax - see comment for details
/* Cannot convert QueryExpressionSyntax, System.NotImplementedException: Conversion for join query clause with condition of kind 'ParenthesizedExpression' not implemented
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.<>c__DisplayClass37_0.<CreateJoinAnonymousObjectKeys>b__0(ValueTuple`2 expression) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 428
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.CreateJoinAnonymousObjectKeys(IEnumerable`1 expressions, SyntaxToken convertIdentifier) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 414
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertJoinClauseAsync(JoinClauseSyntax js) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 0
   at ICSharpCode.CodeConverter.Common.EnumerableExtensions.YieldAsync[T](Task`1 task) in D:\GitWorkspace\CodeConverter\CodeConverter\Common\EnumerableExtensions.cs:line 0
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertQueryBodyClauseAsync(QueryClauseSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 311
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.GetQuerySegmentsAsync(Queue`1 vbBodyClauses) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 99
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertClausesAsync(SyntaxList`1 clauses) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 48
   at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitQueryExpression(QueryExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 681
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 36

Input:
From pCurrent In db.Policies
                            Join pPrevious In db.Policies On pCurrent.Reinsurance_Year - 1 Equals pPrevious.Reinsurance_Year
                            Select Policy_ID
 */
);
        }
    }
}
```

### Details
* Product in use: e.g. both
* Version in use: 9.0.3.0

**Comment by GrahamTheCoder** [comment]
Sorry I didn't spot this when you opened it. Thanks for whittling it down to the core of the issue. Should be a pretty easy fix it's just a case of calling SkipIntoParens in the right spot
