### ISSUE TITLE
VB -> C#: Query syntax - Group by contains different contents

### ISSUE THREAD

**Issue by HeinziAT** [icsharpcode/CodeConverter#948]
### VB.NET code

```
Imports System.Collections.Generic
Imports System.Linq

Class C
    Public Property MyString As String
End Class

Public Module Module1
    Public Sub Main()
        Dim list As New List(Of C)()
        Dim result = From f In list
                     Group f By f.MyString Into Group
                     Order By MyString
	End Sub
End Module
```

### Actual output

```
using System.Collections.Generic;

internal partial class C
{
    public string MyString { get; set; }
}

public static partial class Module1
{
    public static void Main()
    {
        var list = new List<C>();
        var result = default
#error Cannot convert QueryExpressionSyntax - see comment for details
 /* Cannot convert QueryExpressionSyntax, System.NullReferenceException: Object reference not set to an instance of an object.
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.<>c.<GetGroupIdentifier>b__30_2(ExpressionRangeVariableSyntax k) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 346
    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.GetGroupIdentifier(GroupByClauseSyntax gs) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 341
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.CreateGroupByContinuation(GroupByClauseSyntax gcs, SyntaxList`1 convertedClauses, SelectOrGroupClauseSyntax selectOrGroupClauseSyntax) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 210
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertSubQueryAsync(SyntaxToken reusableCsFromId, QueryClauseSyntax clauseEnd, QueryBodySyntax nestedClause, SyntaxList`1 convertedClauses) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 194
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertQueryWithContinuationAsync(Queue`1 querySectionsReversed, SyntaxToken reusableCsFromId) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 162
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertQuerySegmentsAsync(IEnumerable`1 querySegments, SyntaxToken reusableFromCsId, FromClauseSyntax fromClauseSyntax) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 124
    at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertClausesAsync(SyntaxList`1 clauses) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 49
    at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitQueryExpression(QueryExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 681
    at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 36

 Input:
 From f In list
                      Group f By f.MyString Into Group
                      Order By MyString

  */;
    }
}
```

### Expected output

(reduced to the LINQ part for brevity)

```
        var result = from f in list
                     group f by new { f.MyString } into someTempVariable
                     orderby someTempVariable.Key.MyString
                     select new
                     {
                         someTempVariable.Key.MyString,
                         Group = someTempVariable.AsEnumerable()
                     };
```
(...or something similar - I am aware that there are subtle annoying differences in the return types of VB's Group By vs C#'s groupby. I only added the expected output for completeness, the main point of this issue is to report the NRE.)

### Details

Reproducible with the current (2022-10-29) version of the online converter as well as with v9.0.4.0 of the VS extension.

**Comment by GrahamTheCoder** [comment]
I've tried to fix the NRE, but haven't fixed the select/orderby part so I'll leave this open. The output is now 

```csharp
using System.Collections.Generic;
using System.Linq;

internal partial class C
{
    public string MyString { get; set; }
}

public static partial class Module1
{
    public static void Main()
    {
        var list = new List<C>();
        var result = from f in list
                     group f by f.MyString into @group
                     orderby MyString
                     select @group;
    }
}
```
CS0103: The name 'MyString' does not exist in the current context

Expected: As you stated above
