### ISSUE TITLE
VB -> C#: Cannot convert ClassBlockSyntax Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by GenElectric** [icsharpcode/CodeConverter#979]
### VB.Net input code
```vbnet
 Private Sub DGV_AuditsCOL_ColumnHeaderMouseClick(ByVal sender As Object, ByVal e As DataGridViewCellMouseEventArgs) Handles DGV_AuditsCOL.ColumnHeaderMouseClick
' Nothing
End Sub
```

### Erroneous output
```C#

class _failedMemberConversionMarker1
{
}
#error Cannot convert ClassBlockSyntax - see comment for details
/* Cannot convert ClassBlockSyntax, CONVERSION ERROR: Object reference not set to an instance of an object. in 'Public Class VisualBasicCla...' at character 0
   at ICSharpCode.CodeConverter.CSharp.HandledEventsAnalyzer.CreateEventContainer(EventContainerSyntax p, SemanticModel semanticModel) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\HandledEventsAnalyzer.cs:line 105
   at ICSharpCode.CodeConverter.CSharp.HandledEventsAnalyzer.<>c__DisplayClass11_0.<HandledEvent>b__2(MethodStatementSyntax _, HandlesClauseItemSyntax e) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\HandledEventsAnalyzer.cs:line 91
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at ICSharpCode.CodeConverter.CSharp.HandledEventsAnalyzer.AnalyzeAsync() in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\HandledEventsAnalyzer.cs:line 0
   at ICSharpCode.CodeConverter.CSharp.DeclarationNodeVisitor.GetMethodWithHandlesAsync(TypeBlockSyntax parentType, IMethodSymbol designerGeneratedInitializeComponentOrNull) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\DeclarationNodeVisitor.cs:line 634
   at ICSharpCode.CodeConverter.CSharp.DeclarationNodeVisitor.ConvertMembersAsync(TypeBlockSyntax parentType) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\DeclarationNodeVisitor.cs:line 211
   at ICSharpCode.CodeConverter.CSharp.DeclarationNodeVisitor.VisitClassBlock(ClassBlockSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\DeclarationNodeVisitor.cs:line 325
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 38

```

### Expected output
```C#
Expecting conversion
```

### Details
* Product in use: Either with Online converted (https://icsharpcode.github.io/CodeConverter/) or VSIX extension 9.1.1 with VS 2019 V 16.11.22
 * Did you see it working in a previous version, which? No
* The original code did not convert, I then stripped out all content, and still does not convert. So far this occurs with DataGridViews and HorizontalScrollBars event handlers (WinForm). Can you help? Thanks.

Expecting something like this:
public class VisualBasicClass
{
    private void DGV_AuditsCOL_ColumnHeaderMouseClick()
    {
    }
}

**Comment by GenElectric** [comment]
Searching/Testing on this subject I came across "Handles" not being converted or causing errors. 
Should we remove all "Handles" from VB.net code?
I have 396 of them, is the Converter able to ignore "Handles" by itself?
Thanks.

**Comment by GenElectric** [comment]
More info: May be I should clarify, the Class is 20,000 lines of code. (The complete Solution is 120,000)
Because the Converter gave the above error when converting that Class individually, I split it into 3 "Partial Class" (smaller). After splitting, I was able to convert the 1st part but only up to the offending "Handles" line shown above. 

In the 1st part there are 93 "Handles" that appear to have converted successfully.
In another attempt I was able to convert Part 2 and Part 3 but not Part 1, I got the same error.

**Comment by GrahamTheCoder** [comment]
Hi. In general, the converter can convert Handles clauses with no problem. I believe that there is currently an issue when the field/property containing the event is contained in a different file to the Handles clause. This has been filed as #977. Let's consolidate any further discussion there. I'll update shortly - I realise that you're trapped between needing to separate files into pieces but then it breaking when you do.
