### ISSUE TITLE
VB -> C#: Null conditional indexer

### ISSUE THREAD

**Issue by jconnop** [icsharpcode/CodeConverter#993]
### VB.Net input code
```vbnet
Public Class VisualBasicClass

    Private Function TestMethod(testArray As Object()) As Boolean
        Return Not String.IsNullOrWhiteSpace(testArray?(0)?.ToString())
    End Function
    
End Class
```

### Erroneous output
```C#

public partial class VisualBasicClass
{

    private bool TestMethod(object[] testArray)
    {
        return !string.IsNullOrWhiteSpace(testArray? default
#error Cannot convert InvocationExpressionSyntax - see comment for details
   /* Cannot convert InvocationExpressionSyntax, System.ArgumentNullException: Value cannot be null. (Parameter 'node')
      at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoForNode(SyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
      at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.ConvertOrReplaceInvocationAsync(InvocationExpressionSyntax node, ISymbol invocationSymbol) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 971
      at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitInvocationExpression(InvocationExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 957
      at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 38

   Input:
   (0)
    */
   ?.ToString());
    }

}
```

### Expected output
```C#
public partial class VisualBasicClass
{

    private bool TestMethod(object[] testArray)
    {
        return !string.IsNullOrWhiteSpace(testArray?[0]?.ToString());
    }

}
```

### Details
* Product in use: both
* Version in use: VS Extension Version 9.1.3.0 / Website latest
* Did you see it working in a previous version, which? No

**Comment by GrahamTheCoder** [comment]
Thanks, should be a pretty straightforward fix in one of the two methods mentioned in the stack trace, either 
 `VisitInvocationExpression` or `ConvertOrReplaceInvocationAsync`
